main_app:
  site: codfw
  kafka:
    broker_list:
      - kafka-main2006.codfw.wmnet:9093
      - kafka-main2007.codfw.wmnet:9093
      - kafka-main2008.codfw.wmnet:9093
      - kafka-main2009.codfw.wmnet:9093
      - kafka-main2010.codfw.wmnet:9093

nutcracker:
  enabled: true
  servers:
    - rdb2011.codfw.wmnet:6379:1 "cp-1"
    - rdb2013.codfw.wmnet:6379:1 "cp-2"

# Until T433881 is resolved, avoid scheduling in codfw rows E and F (where changeprop-jobqueue
# can't reach kafka-main over IPv6, so rdkafka crashes).
#
# Values like "row-e1" here are correct (i.e. match the actual labels on the nodes) even though E1
# is a rack, not a row.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: NotIn
          values:
          - row-e1
          - row-e2
          - row-e3
          - row-e4
          - row-e5
          - row-f1
          - row-f2
          - row-f3
          - row-f4
          - row-f5
