apiVersion: v2
description: Install kube-state-metrics to generate and expose cluster-level metrics
name: kube-state-metrics
version: 7.3.0
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
  wmf/upstreamVersion: 7.3.0
keywords:
  - metric
  - monitoring
  - prometheus
  - infrastructure
home: https://wikitech.wikimedia.org/wiki/Kube-state-metrics
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/
team: https://www.mediawiki.org/wiki/Kubernetes_SIG
maintainers:
  - name: Kubernetes SIG
    email: kubernetes-sig@lists.wikimedia.org