# This file contains settings shared by all apps deployed in dse-k8s-eqiad.
#
# NOTE: This file is shared between production and staging (-next) releases.
#       In the helmfile directory, this is a symlink into a _*_common_/ values file.
#       Edits here affect both staging and production.
#       Release specific settings and overrides belong in release specific values files.
#
# Release specific settings belong in release specific values files.

service:
  deployment: production

app:
  config_files:
    page-trending.properties:
      # We route the event stream config URI through the local envoy proxy for the MW API
      event-stream-config-url: https://meta.wikimedia.org/w/api.php/
      http-client-routes.meta: https://meta.wikimedia.org=http://localhost:6501

      kafka-config.security.protocol: SSL
      kafka-config.ssl.ca.location: /etc/ssl/certs/wmf-ca-certificates.crt

  flinkConfiguration:
    # == Tuning pageview-trending-relative

    "execution.checkpointing.interval": "5m"
    "execution.checkpointing.min-pause": "2m"
    # Default timeout is 10m and a single timed-out checkpoint fails the job.
    "execution.checkpointing.timeout": "20m"
    "execution.checkpointing.tolerable-failed-checkpoints": "3"
    # Let checkpoint barriers overtake buffered data when backpressured.
    "execution.checkpointing.unaligned.enabled": "true"
    "execution.checkpointing.aligned-checkpoint-timeout": "1m"
    # Restore from local disk instead of S3 after a failure.
    "state.backend.local-recovery": "true"

    # Keep the last 24 hours of savepoints.  Savepoint cleanup happens
    # only when the job is running, so if the job is offline e.g. over a weekend,
    # we won't going to lose the latest savepoint.
    "kubernetes.operator.savepoint.history.max.age": 24h

    # Buffer debloating helps reduce the amount of in-flight data
    # and backpressure.
    # https://nightlies.apache.org/flink/flink-docs-release-2.2/docs/ops/state/checkpointing_under_backpressure/#buffer-debloating
    "taskmanager.network.memory.buffer-debloat.enabled": true

    # ==
    "restart-strategy.type": exponential-delay
    "state.backend.type": hashmap
    "state.checkpoint-storage": filesystem
    "state.checkpoints.num-retained": "10"
    "s3.path.style.access": "true"
    # Enables the Kubernetes HA service.
    # Recovery metadata will be stored in a k8s ConfigMap.
    "high-availability.type": KUBERNETES
    # NOTE: HA paths are configured in release specific files.


flink:
  object_store:
    swift_cluster: https://rgw.eqiad.dpe.anycast.wmnet


# Enable egress.  Specific egress policies should either be added in
# environment/k8s cluster specific networkpolicy.egress.dst_nets,
# or automatically configured via discovery.listeners and/or kafka.allowed_clusters,
networkpolicy:
  egress:
    enabled: true


# Enable the service mesh.
mesh:
  enabled: true

discovery:
  listeners:
    - mw-api-int

external_services:
  s3: [eqiad-dpe]
