apiVersion: v1
kind: Secret
metadata:
  name: {{ template "base.name.release" . }}-secret-config
  labels:
    app: {{ template "base.name.chart" . }}
    chart: {{ template "base.name.chartid" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
{{- if .Values.datahub_config.private }}
data: {{- range $k := (keys .Values.datahub_config.private | sortAlpha) }}
  {{ $k }}: {{ get $.Values.datahub_config.private $k | b64enc | quote }}
{{- end -}}
{{- end }}

