app:
  version: v1.4.8-prod

  service:
    user_agent: Test Kitchen UI/1.4 (#experiment-platform)

  logging:
    level: debug

  database:
    database: test_kitchen_staging
    username: test_kitchen_staging

  listeners:
    action_api_basepath: http://127.0.0.1:6500

  idp:
    oidc_url: https://idp.wikimedia.org/oidc
    client_id: test_kitchen_next
    redirect_uri: https://test-kitchen-next.wikimedia.org/login/callback

  growthbook:
    include_gb: true
    include_tk: true
    # http://localhost:6048 is proxied to growthbook-api-next
    api_url: http://localhost:6048/api/v1/experiments
    ui_url: https://growthbook-next.wikimedia.org/experiments
    drafts_validation: false
    drafts_validation_interval: 4

  phabricator:
    api_url: https://phabricator.discovery.wmnet/api/
    enabled: true
    timeout_ms: 5000

ingress:
  gatewayHosts:
    extraFQDNs:
    - test-kitchen-next.wikimedia.org

discovery:
  listeners:
    - mw-api-int-async-ro
    - growthbook-api-next
