apiVersion: v2
description: A Helm chart for Kubernetes
name: kafka-ui
version: 0.0.1
home: https://wikitech.wikimedia.org/somepage
team: Kafka Infrastructure SIG (https://www.mediawiki.org/wiki/Kafka_Infrastructure_SIG)
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
sources:
  - https://github.com/kafbat/kafka-ui
keywords:
  - kafka
