apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- include "base.meta.metadata" (dict "Root" .) | indent 2 }}
spec:
  podSelector:
    matchLabels:
      app: mediawiki
      release: production
  policyTypes:
  {{- if .Values.networkpolicy.egress.enabled }}
    - Egress
  {{- end }}
    - Ingress
  ingress:
    - ports:
      {{- include "mesh.networkpolicy.ingress" . | indent 6 }}
  {{- if .Values.networkpolicy.egress.enabled }}
  egress:
    {{- include "base.networkpolicy.egress-basic" .Values }}
  {{- end }}

---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ template "base.name.release" . }}-egress-sync-pod
spec:
  selector: app == 'mediawiki-dumps-legacy' && component == 'sync-pod'
  types:
  - Egress
  egress:
    {{- if .Values.dumps.rsync.ssh_egress_hosts }}
    - action: 'Allow'
      protocol: TCP
      destination:
        nets:
        {{- range .Values.dumps.rsync.ssh_egress_hosts }}
          - {{ . }}
        {{- end }}
        ports: [22]
    {{- end }}
    {{- range .Values.sync_pod_external_services }}
    - action: Allow
      destination:
        services:
          name: {{ . }}
          namespace: external-services
    {{- end }}

{{ include "base.networkpolicy.egress.external-services" . }}
