# Default values for EventStreams.

docker:
  registry: docker-registry.wikimedia.org
  pull_policy: IfNotPresent

resources:
  replicas: 1

service:
  # valid values are "production" and "minikube" and "none".
  # If "none", no k8s Service will be deployed for this release.
  deployment: minikube
  port:
    name: http # a unique name of lowercase alphanumeric characters or "-", starting and ending with alphanumeric, max length 63
    # protocol: TCP # TCP is the default protocol
    targetPort: 8092 # the number or name of the exposed port on the container
    port: 8092 # the number of the port desired to be exposed to the cluster
    nodePort: null # you need to define this if "production" is used. In minikube environments let it autoallocate
    nodePort: 30892

# EventStreams uses service-runner native prometheus monitoring, not statsd-exporter.
monitoring:
  enabled: true
  # These ports are only used when testing in non production dev env.
  port:
    targetPort: 9102
    port: 9102
    nodePort: 31102

# Additional resources if we want to add a port for a debugger to connect to.
# Debug mode adds the --profile and --inspect flags to the NodeJS service, and
# also deploys a wmfdebug sidecar container in the pod. You can get the v8.log profiling output
# from the pod with e.g (staging):
#   source .hfenv; kubectl cp -n eventstreams -c eventstreams <pod_id>:/tmp/eventstreams-v8.log ./
# You can connect to the Node Inspector on port 9229 for the master service-runner process,
# and port 9230 for the worker process.  Note that if a worker is restarted, it willl
# claim a new port and not be reachable externally.
# You can log into the wmfdebug container with e.g. (staging):
#   source .hfenv; kubectl exec -ti <pod_id> -n eventstreams -c eventstreams bash
debug:
  enabled: false
  # Define here any port that you want to expose for debugging purposes
  # 9229 master and 9230 worker will be used by v8 profiler
  ports: [9229, 9230]

# Declare variables to be passed into your templates.
app:
  image: repos/data-engineering/eventstreams
  version: latest # we use latest everywhere in the defaults.
  port: &app_port 8092 # port exposed as a Service, also used by service-checker.
  metricsPort: 9102
  command: ["nodejs"]
  args: ["/srv/service/server.js", "-c", "/etc/eventstreams/config.yaml"]
  requests:
    cpu: 100m
    memory: 500Mi
  limits:
    cpu: 1000m
    memory: 1000Mi
  liveness_probe:
    tcpSocket:
      port: *app_port
  readiness_probe:
    httpGet:
      path: /_info
      port: *app_port

config:
  public:
    NODE_EXTRA_CA_CERTS: /etc/eventstreams/puppetca.crt.pem
  private: {} # Add here all the keys that should be private but still available as env variables

  name: eventstreams
  port: *app_port

  log_level: info

  # Override this in your service specific values.yaml file
  # to enable Kafka consumer TLS.
  kafka_ca_cert: null

  conf:
    kafka:
      metadata.broker.list: 'kafka.default.svc.cluster.local:31092'
      statistics.interval.ms: 5000
      # Set these to enable Kafka consumer TLS (no authentication, just encryption).
      #security.protocol: ssl
      # These ssl setttings are only used if security.protocol == ssl
      ssl.ca.location: /etc/eventstreams/puppetca.crt.pem
      ssl.cipher.suites: ECDHE-ECDSA-AES256-GCM-SHA384
      ssl.curves.list: P-256
      ssl.sigalgs.list: ECDSA+SHA256

    schema_base_uris:
    - http://localhost:6023/repositories/primary/jsonschema
    - http://localhost:6023/repositories/secondary/jsonschema
    schema_latest_version: latest

    # This must be set in helmfile values.yaml!
    #stream_config_uri:

networkpolicy:
  egress:
    enabled: false

# Basic mesh-related data.
mesh:
  enabled: false
  admin: {port: 1666 }
  image_version: latest
  # http keepalive timeout for incoming requests
  idle_timeout: "4.5s"
  # Port to listen to
  public_port: 4892
  local_access_log_min_code: "200"
  # Headers to add to a local request,
  # in dictionary form.
  request_headers_to_add: []
  # Timeout of a request to the local service
  upstream_timeout: "60s" 
  # Enabling telemetry, telemetry port.
  telemetry:
    enabled: false
    port: 9361
  # Extra set of label / value to use in the mesh Service label selector.
  # Use this when you have multiple pods with different functionalities
  # in the namespace, to make sure the traffic only goes to the appropriate one.
  extra_service_selector_labels: {}
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

# Mesh related pure TCP proxies
tcp_proxy:
  listeners: []

# Should be provided by configuration management.
# See details of the structures in the comments
# In the configuration module.
services_proxy: ~
tcp_services_proxy: ~

# Mesh-related discovery
# TODO: move under mesh.* once we can
discovery:
  # List of listeners. These should match service mesh endpoint names
  # (defined in https://gerrit.wikimedia.org/g/operations/puppet/+/refs/heads/production/hieradata/common/profile/services_proxy/envoy.yaml)
  listeners:
    - schema      # schema.discovery.wmnet

# The set of external services to allow egress to
# Example:
# kafka:
# - main-codfw
# - main-eqiad
# presto:
# - analytics
#
# See https://wikitech.wikimedia.org/wiki/Kubernetes/Deployment_Charts#Enabling_egress_to_services_external_to_Kubernetes
# for the list of supported services
external_services: {}

# Allow external traffic to reach this service via a (cluster provided) ingress controller.
# https://wikitech.wikimedia.org/wiki/Kubernetes/Ingress#Configuration_(for_service_owners)
ingress:
  enabled: false
  # By default, enabling ingress will switch the charts services from type NodePort to
  # ClusterIP. While that is fine for new services it may not be desired during transition
  # of existing ones from dedicated LVS to Ingress.
  # By setting keepNodePort to true, the services will stay of type NodePort.
  keepNodePort: true
  # gatewayHosts settings configure the hostnames this service will be reachable on.
  # By default, this will be a list like:
  # - {{ gatewayHosts.default }}.{{ domain }}
  # For all domains listed in .gatewayHosts.domains (specified by SRE for each environment)
  gatewayHosts:
    # default will expand to {{ .Release.Namespace }} as long as it is an empty string.
    default: ""
    # disableDefaultHosts may be set to true if the service should not be reachable via
    # the gateway hosts generated by default (see above).
    disableDefaultHosts: false
    # extraFQDNs is a list of extra FQDNs this service should be reachable on.
    # It can be used to extend the gateway hosts that are generated by default.
    extraFQDNs: []
  # If you want to attach routes of this release to an existing Gateway, provide the name
  # of that gateway here in the format: <namespace>/<gateway-name>
  # This is useful if you wish to make multiple releases available from the same hostname.
  existingGatewayName: ""
  # routeHosts is a list of FQDNs the httproutes should attach to.
  # If existingGatewayName not set, this list might be empty and will default to the gateway
  # host generated according to how .Values.gatewayHosts.* is configured.
  # If existingGatewayName is set, you need to provide the FQDNs your routes should attach to.
  routeHosts: []
  # HTTPRoute routing rules. By default https://<hosts from above>/ will be routed to
  # the service without modification.
  # Docs: https://istio.io/v1.9/docs/reference/config/networking/virtual-service/#HTTPRoute
  httproutes: []
  # Base CORS HTTP headers for the general use case.
  base_cors_policy: false
  # Add a custom CORS policy, injecting an Istio CorsPolicy config:
  # https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy
  # Takes precedence over base_cors_policy.
  custom_cors_policy: {}
  # Add a list of destination rule hosts to allow httproute rules to address more than 1 backend services.
  # NOTE: The list needs to be a list of kubernetes service DNS names
  destinationrulehosts: []

# The httpd-cas sidecar manages CAS authentication for turnilo, redirecting to the main app when authenticated.
auth_proxy:
  enabled: false
  httpd_cas:
    image: httpd-cas
    version: latest # we use latest everywhere in the defaults.
    # Port that CAS will listen on
    port: 8444
    # Port that CAS will proxy to
    target_port: *app_port
    site:
      # HTTP virtualhost that CAS proxy will handle
      server_name: override_me
      # URL that users will see, see
      # https://github.com/apereo/mod_auth_cas/blob/9acbc6239f35f291d3b166f897bdda012adf5cea/README#L217
      cas_root_proxied_as: override_me
      cas_login_url: https://idp.wikimedia.org/login
      cas_validate_url: https://idp.wikimedia.org/serviceValidate
      cas_ldap_groups: [nda, wmf]
      health_check_path: /var/www/health_check
      conf_name: 50-httpd-cas
      cas_debug: "Off"
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 400Mi
    cookies_path: /var/cache/apache2/mod_auth_cas/
    cookies_size_limit: 100Mi

# Add here the list of kafka-clusters (by name) that the service will need to reach.
kafka:
  allowed_clusters: []

# Optional affinity settings
affinity: {}

cronjobs: {}
