app:
  image: repos/sre/etherpad
  version: 2026-09-15-130704
  requests:
    cpu: 500m
    memory: 500Mi
  limits:
    cpu: 1000m 
    memory: 1000Mi

docker:
  registry: docker-registry.discovery.wmnet
  pull_policy: IfNotPresent

mesh:
  enabled: true
  # The port on which envoy will be listening. Given we're enabling ingress,
  # this will only be internal to the cluster and doesn't need to be unique
  public_port: 8000
  certmanager:
    extraFQDNs:
      - etherpad.wikimedia.org
      - etherpad-next.wikimedia.org

ingress:
  enabled: true
  gatewayHosts:
    extraFQDNs:
    - etherpad.wikimedia.org
    - etherpad-next.wikimedia.org

config:
  public:
    DB_TYPE: "mysql"
    DB_HOST: "m1-master.eqiad.wmnet"
    DB_PORT: "3306"
    DB_NAME: "etherpad"
    DB_USER: "etherpad"

mariadb:
  egress:
    sections: ["m1"]

networkpolicy:
  egress:
    enabled: true