{{- if .Values.defaultConfiguration.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flink-operator.labels" . | nindent 4 }}
data:
  config.yaml: |+
{{- if .Values.defaultConfiguration.append }}
  {{- $.Files.Get "conf/flink-conf.yaml"  | nindent 4 -}}
{{- end }}
{{- if hasKey (.Values.defaultConfiguration) "config.yaml" }}
  {{- index (.Values.defaultConfiguration) "config.yaml" | nindent 4 -}}
{{- end }}
{{- if .Values.watchNamespaces }}
    kubernetes.operator.watched.namespaces: {{ join "," .Values.watchNamespaces  }}
{{- end }}
{{- if index .Values "operatorHealth" }}
    kubernetes.operator.health.probe.enabled: true
    kubernetes.operator.health.probe.port: {{ .Values.operatorHealth.port }}
{{- end }}
  flink-conf.yaml: |+
{{- if .Values.defaultConfiguration.append }}
  {{- $.Files.Get "conf/flink-conf.yaml"  | nindent 4 -}}
{{- end }}
{{- if hasKey (.Values.defaultConfiguration) "flink-conf.yaml" }}
  {{- index (.Values.defaultConfiguration) "flink-conf.yaml" | nindent 4 -}}
{{- end }}
{{- if .Values.watchNamespaces }}
    kubernetes.operator.watched.namespaces: {{ join "," .Values.watchNamespaces  }}
{{- end }}
{{- if index .Values "operatorHealth" }}
    kubernetes.operator.health.probe.enabled: true
    kubernetes.operator.health.probe.port: {{ .Values.operatorHealth.port }}
{{- end }}
  log4j-operator.properties: |+
{{- if .Values.defaultConfiguration.append }}
  {{- $.Files.Get "conf/log4j-operator.properties"  | nindent 4 -}}
{{- end }}
{{- if index (.Values.defaultConfiguration) "log4j-operator.properties" }}
  {{- index (.Values.defaultConfiguration) "log4j-operator.properties" | nindent 4 -}}
{{- end }}
  log4j-console.properties: |+
{{- if .Values.defaultConfiguration.append }}
  {{- $.Files.Get "conf/log4j-console.properties"  | nindent 4 -}}
{{- end }}
{{- if index (.Values.defaultConfiguration) "log4j-console.properties" }}
  {{- index (.Values.defaultConfiguration) "log4j-console.properties" | nindent 4 -}}
{{- end }}

{{- end }}
