apiVersion: v2
description: A Helm chart for Citoid on WMF Kubernetes infrastructure
kubeVersion: ">=1.8"
name: citoid
version: 0.3.20
keywords:
  - citation
  - citoid
  - extension
home: https://wikitech.wikimedia.org/wiki/Citoid
team: https://wikitech.wikimedia.org/wiki/Editing_team
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/mediawiki/services/citoid,general
maintainers:
  - name: Marielle Volz
    email: mvolz@wikimedia.org
