main_app:
  image: repos/sre/hoarde
  version: v1.4.1
  command: ["./hoarde"]
  args: ["-config", "/etc/cassandra-http-gateway/config.yaml"]
  service_name: linked-artifacts
  consistency: local_quorum

  # note the "_"
  cassandra_user: "linked_artifacts"
  cassandra_keyspace: linked_artifacts

  hoarde:
    tables:
      article_topics:
        lambda:
          type: kserve_v2
          hostname: inference.discovery.wmnet
          port: 30443
          timeout: 5s
          model_name: outlink-topic-model
          content_type: application/json
          tls:
            ca: /etc/ssl/certs/ca-certificates.crt
            authority: outlink-topic-model-grpc.articletopic-outlink.wikimedia.org

  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    cpu: 1
    memory: 1024Mi

resources:
  replicas: 4

mesh:
  enabled: true

ingress:
  enabled: true

monitoring:
  enabled: true
