main_app:
  log_level: debug

  hoarde:
    tables:
      echo:
        lambda:
          type: grpc
          hostname: cassandra-dev2001-a.codfw.wmnet
          port: 50051
          timeout: 2000ms

resources:
  replicas: 1

ingress:
  staging: true

# Added temporarily for testing — T421444
networkpolicy:
  egress:
    enabled: true
    dst_nets:
      - cidr: 10.192.16.14/32 # cassandra-dev2001-a
        ports:
          - protocol: tcp
            port: 50051
