opensearchCluster:
  general:
    serviceName: "opensearch-toolhub"
    image: docker-registry.discovery.wmnet/repos/data-engineering/opensearch:3@sha256:23ed4054bcf07110e5f2a37d6aa7087ceddeb503ac54118dbe7027a7d522095f
  anonymous_all_indices: true

certificate:
  extraFQDNs:
  - opensearch-toolhub.discovery.wmnet
