config:
# Keys are capitalized and prefixed with MATOMO_ when injected as environment variables,
# ref https://plugins.matomo.org/EnvironmentVariables .
# > Override any Matomo config with environment variables. 
# > To overwrite any setting simply specify an environment variable in the following format:
# > MATOMO_$CATEGORY_$SETTING
  # Deployment secrets override public defaults; omit the MATOMO_ prefix from keys.
  public:
    DATABASE_DBNAME: matomo-next
    DATABASE_HOST: '10.64.32.25' # matomo1003.eqiad.wmnet
    DATABASE_SCHEMA: 'Mariadb'
    DATABASE_TABLES_PREFIX: matomo_
    DATABASE_USERNAME: matomo-next
    GENERAL_MAIL_USERNAME: 'wmf-admin'
ingress:
  enabled: true
  # By default, enabling ingress will switch the charts services from type NodePort to
  # ClusterIP. While that is fine for new services it may not be desired during transition
  # of existing ones from dedicated LVS to Ingress.
  # By setting keepNodePort to true, the services will stay of type NodePort.
  keepNodePort: false
  # gatewayHosts settings configure the hostnames this service will be reachable on.
  # By default, this will be a list like:
  # - {{ gatewayHosts.default }}.{{ domain }}
  # For all domains listed in .gatewayHosts.domains (specified by SRE for each environment)
  gatewayHosts:
    # default will expand to {{ .Release.Namespace }} as long as it is an empty string.
    default: ""
    # disableDefaultHosts may be set to true if the service should not be reachable via
    # the gateway hosts generated by default (see above).
    disableDefaultHosts: false
    # extraFQDNs is a list of extra FQDNs this service should be reachable on.
    # It can be used to extend the gateway hosts that are generated by default.
    extraFQDNs:
      - 'matomo-next.svc.eqiad.wmnet'
      - 'matomo-next.wikimedia.org'

# enable egress traffic to the database
networkpolicy:
  egress:
    enabled: true
    dst_nets:
      - cidr: 10.64.32.25/32  # matomo1003.eqiad.wmnet
        ports:
        - protocol: TCP
          port: 3306