# Setup for the [staging cluster](https://wikitech.wikimedia.org/wiki/Kubernetes/Clusters#staging).
# The staging cluster uses real upstream services, but not all are available.
# Its purpose is to verify a release of the REST gateway before it gets applied to the
# production clusters.

resources:
  replicas: 1

# Settings for the end-to-end tests defined under tests/e2e.
smokepy:
  gateway:
    # The target URL to use for end-to-end tests.
    # Can also be set using $GATEWAY_TEST_TARGET_URL.
    target_url: https://staging.svc.eqiad.wmnet:4113
    host: en.wikipedia.org
    headers: {}

    # The path of the endpoint to probe when testing the default rate limit policy.
    default_policy_endpoint: "/en.wikipedia.org/v1/page/title/X"

    # The path of the endpoint to probe when testing the shadow rate limit policy.
    # Doesn't have to be an existing action API module since missing modules still produce status 200.
    shadow_policy_endpoint: "/w/api.php?action=shadowed&format=json"

    # The path of the endpoint to probe when testing for RESTbase compatibility CORS behavior
    cors_rb_compat_endpoint: "/en.wikipedia.org/v1/page/title/X"

    # The path of the endpoint to probe when testing default CORS behavior for upstream responses
    cors_upstream_endpoint: "/w/api.php?action=query&meta=siteinfo&format=json"

    # Endpoint that should be exempt from JWT checks
    jwt_exempt_endpoint: "/w/rest.php/oauth2/"

    # Endpoint that should require a JWT
    jwt_required_endpoint: "/w/api.php?action=compare&format=json"

main_app:
  # enable debug logging in staging
  args: ["-l", "debug"]
  domains:
    - staging.svc.eqiad.wmnet:*
    - staging.svc.eqiad.wmnet
    - rest-gateway.discovery.wmnet:*
    - rest-gateway.discovery.wmnet
    - rest-gateway-ro.discovery.wmnet:*
    - rest-gateway-ro.discovery.wmnet
    - "*.wikipedia.org"
    - "*.m.mediawiki.org"
    - "*.m.wikibooks.org"
    - "*.m.wikidata.org"
    - "*.m.wikimedia.org"
    - "*.m.wikimediafoundation.org"
    - "*.m.wikinews.org"
    - "*.m.wikipedia.org"
    - "*.m.wikiquote.org"
    - "*.m.wikisource.org"
    - "*.m.wikiversity.org"
    - "*.m.wikivoyage.org"
    - "*.m.wiktionary.org"
    - "*.mediawiki.org"
    - "*.planet.wikimedia.org"
    - "*.wikibooks.org"
    - "*.wikidata.org"
    - "*.wikimedia.org"
    - "*.wikimediafoundation.org"
    - "*.wikinews.org"
    - "*.wikiquote.org"
    - "*.wikisource.org"
    - "*.wikiversity.org"
    - "*.wikivoyage.org"
    - "*.wiktionary.org"
    - "*.wmfusercontent.org"
    - "*.zero.wikipedia.org"
    - mediawiki.org
    - w.wiki
    - wikibooks.org
    - wikidata.org
    - wikimedia.org
    - wikimediafoundation.org
    - wikinews.org
    - wikiquote.org
    - wikisource.org
    - wikiversity.org
    - wikivoyage.org
    - wiktionary.org
    - wmfusercontent.org
    - wikipedia.org
    # required for service mesh
    - "localhost:6033"
  ratelimiter:
    enabled: true
    lua_hook_enabled: true
    log_level: debug
    redis_host: localhost
    redis_port: 6379
    key_prefix: "staging_restgw_"
    key_log_format: "%REQ(x-wmf-ratelimit-class)%:%REQ(x-wmf-user-id)%@%REQ(x-wmf-ratelimit-policy)%"
    envoy_timeout: 0.5
    anon_class_by_address:
      "11.22.33.": "anon-cgnat"
    units: [ MINUTE ]
    policies:
      "Mar2026":
        shadow_mode: false # enable on staging for testing
        limits:
          "*": # catch-all limits
            MINUTE: 1
          "anon": # no auth, not a browser, no good User-Agent, no known IP
            MINUTE: 1
          "anon-browser": # no auth, but looks like a browser
            MINUTE: 3
          "anon-cgnat": # clients behind a CGNAT
            MINUTE: 5
          "unauthed-bot": # no auth, but good User-Agent -- temp?
            MINUTE: 7
          "unauthed-mediawiki": # InstantCommons and such
            MINUTE: 9
          "authed-user": # valid JWT
            MINUTE: 11
          "established-user": # valid JWT, meets age/edit count criteria
            MINUTE: 13
          "highlimits-user": # valid WT and member of specific global groups
            MINUTE: 15
          "approved-bot": # bot approved by the community
            MINUTE: 17
          "known-client": # no auth, network associated with a known client
            MINUTE: 19
          "known-network": # no auth, network under outbound control (WMCS, WME)
            MINUTE: 21

      "Apr2026":
        shadow_mode: true
        limits:
          "*": # catch-all limits
            MINUTE: 1
          "anon": # no auth, not a browser, no good User-Agent, no known IP
            MINUTE: 1
          "anon-browser": # no auth, but looks like a browser
            MINUTE: 3
          "anon-cgnat": # clients behind a CGNAT
            MINUTE: 5
          "unauthed-bot": # no auth, but good User-Agent -- temp?
            MINUTE: 7
          "unauthed-mediawiki": # InstantCommons and such
            MINUTE: 9
          "authed-user": # valid JWT
            MINUTE: 11
          "established-user": # valid JWT, meets age/edit count criteria
            MINUTE: 13
          "highlimits-user": # valid WT and member of specific global groups
            MINUTE: 15
          "approved-bot": # bot approved by the community
            MINUTE: 17
          "known-client": # no auth, network associated with a known client
            MINUTE: 19
          "known-network": # no auth, network under outbound control (WMCS, WME)
            MINUTE: 21

      "AbstractWiki":
        shadow_mode: false
        limits:
          "*": # catch-all limits
            MINUTE: 10
          "anon": # no auth, not a browser, no good User-Agent, no known IP
            MINUTE: 10
          "anon-browser": # no auth, but looks like a browser
            MINUTE: 30
          "anon-cgnat": # clients behind a CGNAT
            MINUTE: 50
          "unauthed-bot": # no auth, but good User-Agent -- temp?
            MINUTE: 70
          "unauthed-mediawiki": # InstantCommons and such
            MINUTE: 90
          "authed-user": # valid JWT
            MINUTE: 110
          "established-user": # valid JWT, meets age/edit count criteria
            MINUTE: 130
          "highlimits-user": # valid WT and member of specific global groups
            MINUTE: 150
          "approved-bot": # bot approved by the community
            MINUTE: 170
          "known-client": # no auth, network associated with a known client
            MINUTE: 190
          "known-network": # no auth, network under outbound control (WMCS, WME)
            MINUTE: 210

    enable_x_ratelimit_headers: true

  access_log:
    debug: true
    sample_percentage: 100
    ratelimit_sample_percentage: 100

  # NOTE: extra_rest_gateway_routes is prepended to the normal rest_gateway_routes
  # to allow us to test features that are not yet present on any production route.
  extra_rest_gateway_routes:
    # Fake API module for testing test shadow mode
    - name: mw-action-api-shadowed
      # We set a higher timeout to allow for long queries on the search API
      timeout: 53s
      # Exclude cspreports action API calls from rate limits
      cluster: mw-api-ext-ro
      csp_enabled: false
      urls:
        - name: shadowed
          in: '/+w/api.php(.*)'
          out: '/w/api.php\1'
          query_parameters:
            - name: action
              string_match:
                # this does not exist in the real API
                exact: 'shadowed'
                ignore_case: true
      rate_limit_policies: [ "Apr2026", "BYPASS" ]

    - name: staging-mw-action-api-jwt-required
      timeout: 53s
      # Require JWT for action=compare, just to test the mechanism.
      # The JWT can be provided as a bearer token or as a session cookie.
      jwt: required
      cluster: mw-api-ext-ro
      csp_enabled: false
      urls:
        - name: compare
          in: '/+w/api.php(.*)'
          out: '/w/api.php\1'
          query_parameters:
            - name: action
              string_match:
                exact: 'compare'
                ignore_case: true

  discovery_endpoints:
    citoid:
      ingress: true
      port: 30443 # ingress
      tls: true
      internal_host: citoid.k8s-staging.discovery.wmnet
    geo-analytics:
      internal_host: geo-analytics.k8s-staging.discovery.wmnet
      tls: true
      port: 30443
    media-analytics:
      internal_host: media-analytics.k8s-staging.discovery.wmnet
      tls: true
      port: 30443
    mobileapps:
      internal_host: mobileapps.k8s-staging.discovery.wmnet
      tls: true
      port: 30443
    proton:
      internal_host: proton.k8s-staging.discovery.wmnet
      tls: true
      port: 30443
    wikifeeds:
      internal_host: wikifeeds.k8s-staging.discovery.wmnet
      tls: true
      port: 4101
    device-analytics:
      internal_host: device-analytics.k8s-staging.discovery.wmnet
      port: 30443
      tls: true
    page-analytics:
      internal_host: page-analytics.k8s-staging.discovery.wmnet
      port: 30443
      tls: true
    edit-analytics:
      internal_host: edit-analytics.k8s-staging.discovery.wmnet
      port: 30443
      tls: true
    editor-analytics:
      internal_host: editor-analytics.k8s-staging.discovery.wmnet
      port: 30443
      tls: true
    commons-impact-analytics:
      internal_host: commons-impact-analytics.k8s-staging.discovery.wmnet
      port: 30443
      tls: true
    mw-api-ext-ro:
      tls: true
      port: 4447
    linkrecommendation:
      internal_host: staging.svc.eqiad.wmnet
      tls: true
      port: 4005

nutcracker:
  enabled: true
  version: 0.0.4
  servers:
    - rdb1011.eqiad.wmnet:6380:1 "ratelimit-1"
    - rdb1013.eqiad.wmnet:6380:1 "ratelimit-2"

# Only used by ratelimiter for metrics - envoy uses prometheus native metrics
monitoring:
  enabled: true
