apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "base.meta.metadata" (dict "Root" .) | indent 2 }}
spec:
  selector:
  {{- include "base.meta.selector" . | indent 4 }}
  replicas: {{ .Values.resources.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "base.meta.pod_labels" . | indent 8 }}
        mirror_name: {{ $.Release.Name }}
      annotations:
        {{- include "base.meta.pod_annotations" . | indent 8 }}
        {{- if $.Values.monitoring.enabled }}
        prometheus.io/port: "{{ $.Values.monitoring.prometheus_port }}"
        prometheus.io/path: "/"
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      {{- toYaml .Values.affinity | nindent 6 }}
      {{- end }}
      initContainers:
      - name: {{ template "base.name.release" . }}-sed
        image: {{ template "app.generic._image" . }}
        imagePullPolicy: {{ .Values.docker.pull_policy }}
        command: ['sh']
        args:
        - -c
        - |
          cp /etc/mirrormaker-tpl/* /etc/mirrormaker/ && sed "s/env_HOSTNAME/${HOSTNAME}/g" /etc/mirrormaker-tpl/producer.properties > /etc/mirrormaker/producer.properties
        resources:
          requests:
            cpu: 256m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        {{- include "base.helper.restrictedSecurityContext" . | indent 8 }}
        volumeMounts:
        - name: kafka-mirrormaker-tpl
          mountPath: /etc/mirrormaker-tpl
        - name: kafka-mirrormaker-config
          mountPath: /etc/mirrormaker
      containers:
        {{- include "app.generic.container" . | indent 8 }}
      volumes:
        {{- tpl (include "app.generic.volume" .) . | indent 8 }}



