#!/usr/bin/env python3
# Forked from https://gist.github.com/nosmo/306d50581f4069958206d772b6d49176

"""Check a git commit for changes to charts with no bumps of Chart.yaml"""

import os
import re
import subprocess
import sys


def check_amend() -> bool:
    ppid = os.getppid()
    ps_output = subprocess.run(
            ["ps", "-f", "-p", str(ppid)],
            capture_output=True,
            check=True,
            encoding='utf-8'
            )
    return "--amend" in ps_output.stdout


def main():

    if check_amend():
        sys.exit(0)

    cmd = ['git', 'diff', '--cached', '--name-only']
    changed_files = subprocess.run(
            cmd,
            capture_output=True,
            check=True,
            encoding='utf-8'
            )
    changed_charts = set()
    bumped_charts = set()

    for changed_file in changed_files.stdout.strip().split("\n"):
        chart_match = re.match("^charts/([\w-]+)/(.*)", changed_file)
        if chart_match:
            chartname, chartrest = chart_match.groups()

            changed_charts.add(chartname)
            if chartrest == "Chart.yaml":
                bumped_charts.add(chartname)

    not_bumped = changed_charts.difference(bumped_charts)
    if not_bumped:
        print("Charts changed without Chart.yaml bumped: {}".format(
            ",".join(not_bumped))
            )
        sys.exit(1)


if __name__ == "__main__":
    main()
