apiVersion: v2
description: A Helm chart for running statsd-exporter for the production MediaWiki installation at the wikimedia foundation
name: statsd-exporter
version: 0.0.12
keywords:
  - statsd
  - prometheus
  - monitoring
  - infrastructure
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/115px-Prometheus_software_logo.svg.png
home: https://wikitech.wikimedia.org/wiki/Statsd-exporter
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/operations/docker-images/production-images
  - https://github.com/prometheus/statsd_exporter
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: SRE Service Operations
    email: sre-service-ops@wikimedia.org
