apiVersion: v2
description: A Helm chart for the Chart extension chart-renderer service
name: chart-renderer
version: 0.0.11
home: https://wikitech.wikimedia.org/wiki/Chart_renderer
sources:
  - https://gitlab.wikimedia.org/repos/mediawiki/services/chart-renderer
team: https://wikitech.wikimedia.org/wiki/Reader_Growth
maintainers:
  - name: Katie Filbert
    email: kfilbert@wikimedia.org