---
csiConfig:
  - clusterID: &clusterid "8e69717a-518b-4c00-9f96-0635d9b913c6"
    monitors:
      - "cephosd2001:6789"
      - "cephosd2002:6789"
      - "cephosd2003:6789"

nodeplugin:
  httpMetrics:
    enabled: false
  registrar:
    image:
      repository: docker-registry.discovery.wmnet/repos/data-engineering/kubernetes/csi/csi-node-driver-registrar
      tag: 2026-09-21-110728-306e18f10e1e7869bddcd8daca94d2927774f8e6@sha256:d0ad01310fd8e0d3ce8218db514a2bf9a1e4bb5697af0c8714f2749a7e8fbc89
  plugin:
    image:
      repository: docker-registry.discovery.wmnet/repos/data-engineering/ceph-csi
      tag: 2026-09-18-134456-904779674c9496bf744cb072864906505607d2bf@sha256:1cf0d13631f0c5dd9d4fda80bc5b67c2ae4956a99193f69136476a23bb678776
  tolerations:
  # allow the ceph-csi-rbd pods to run on dedicated workers,
  # as the workload might still require access to Ceph rbd volumes.
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "dedicated"
    operator: "Exists"
    effect: "NoExecute"

provisioner:
  provisioner:
    image:
      repository: docker-registry.discovery.wmnet/repos/data-engineering/kubernetes/csi/csi-provisioner
      tag: 2026-09-21-110728-306e18f10e1e7869bddcd8daca94d2927774f8e6@sha256:5b4b3b52b0663963879089e3c1ec86e5f0947f06c8ec12c326b0b49b75d48626
  attacher:
    image:
      repository: docker-registry.discovery.wmnet/repos/data-engineering/kubernetes/csi/csi-attacher
      tag: 2026-09-21-110728-306e18f10e1e7869bddcd8daca94d2927774f8e6@sha256:3fbc647df78586ce0ffa0fe22fb0834b5567e4dadd68845aec325ea229686781
  resizer:
    image:
      repository: docker-registry.discovery.wmnet/repos/data-engineering/kubernetes/csi/csi-resizer
      tag: 2026-09-21-110728-306e18f10e1e7869bddcd8daca94d2927774f8e6@sha256:34bede5dc15e585f33a1ad9ecbd57b8fc8289b168d27900149ebe4cd916e6e20
  snapshotter:
    enabled: false

storageClass:
  create: true
  classes:
  - name: ceph-rbd-ssd
    clusterID: *clusterid
    pool: dse-k8s-csi-rbd-ssd
  - name: ceph-rbd-hdd
    clusterID: *clusterid
    pool: dse-k8s-csi-rbd-hdd

secret:
  create: true
  userID: dse-k8s-csi
  # userKey: # This value has been added helmfile via the private repo

# The list of namespaces using ceph-cephfs PVCs. If you plan to use such a PVC in a new namespace,
# you'll need to add it in there (please keep the list sorted, after the kube-system entry)
# and apply admin_ng
tenantNamespaces:
- kube-system
- analytics
- analytics-test
- opensearch-apifeatureusage
- opensearch-apifeatureusage-test
- opensearch-ipoid
- opensearch-ipoid-test
- opensearch-semantic-search
- opensearch-semantic-search-test
- opensearch-test
- opensearch-toolhub
- opensearch-toolhub-test
- opensearch-ttmserver
- opensearch-ttmserver-test
- wdqs
- wdqs-next
