namespaces:
  echoserver: {}
  opensearch-test:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "16Gi"
          cpu: "8"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "20Gi"
          cpu: "12"
  opensearch-ipoid-test:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "16Gi"
          cpu: "8"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "20Gi"
          cpu: "12"
  opensearch-ipoid:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "16Gi"
          cpu: "8"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "20Gi"
          cpu: "12"
  opensearch-semantic-search:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "40Gi"
          cpu: "8"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "40Gi"
          cpu: "12"
  opensearch-semantic-search-test:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "32Gi"
          cpu: "8"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "32Gi"
          cpu: "12"
  opensearch-toolhub:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
  opensearch-toolhub-test:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
  opensearch-apifeatureusage:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
  opensearch-apifeatureusage-test:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
  opensearch-ttmserver:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
  opensearch-ttmserver-test:
    limitranges:
      container:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"
        defaultRequest:
          memory: "2000Mi"
          cpu: "500m"
        default:
          memory: "2000Mi"
          cpu: "500m"
      pod:
        min:
          memory: "300Mi"
          cpu: "100m"
        max:
          memory: "4Gi"
          cpu: "2"

