app:
  port: &proxyport 443

backend:
  volume:
    name: data-dir
    storageType: emptyDir # Can be set to emptyDir or pvc
    storageClass: none # only used if storageType == pvc
    size: 1Mi # dummy value
  security:
    gid: 900 # default runuser as created by blubber

qlever:
  image: repos/wikidata-platform/wdqs/wdqs-qlever
  version: latest
  port: 7001
  # The "current" dir is created and populated by the "init" container
  workingDir: /srv/data/current
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 4
    memory: 32Gi
  volumeMounts:
   - name: data-dir
     mountPath: /srv/data
  config:
    public:
      QLEVER_PORT: 7001
      QLEVER_MAX_MEM: 24G
      QLEVER_MAX_CACHE: 8G
      QLEVER_NUM_QUERIES: 50
  service:
    port:
      name: http # a unique name of lowercase alphanumeric characters or "-", starting and ending with alphanumeric, max length 63
      # protocol: TCP # TCP is the default protocol
      targetPort: 7001 # the number or name of the exposed port on the container
      port: 7001 # the number of the port desired to be exposed to the cluster

init:
  image: repos/wikidata-platform/wdqs/wdqs-backend-init
  version: latest
  config:
    public:
      # A stable Kafka group bound to the storage and pod, due to usage of StatefulSet
      KAFKA_GROUP: $(K8S_POD_NAMESPACE)-$(K8S_POD_NAME)
      # As long as the Qlever index is not persisted regularly, we need to rebuild from dump ts on each restart
      KAFKA_FORCE_SEEK: true
      NEW_INDEX_S3_HOST: rgw.eqiad.dpe.anycast.wmnet
      NEW_INDEX_S3_BUCKET: wdqs-update-pipeline
      LOGGER: ecs
    private:
      # The actual values are automatically injected from /etc/helmfile-defaults/private via the helmfile
      S3_ACCESS_KEY: accesskey
      S3_SECRET_KEY: privatekey
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 512Mi
  volumeMounts:
   - name: data-dir
     mountPath: /srv/data

consumer:
  image: repos/wikidata-platform/wdqs/wdqs-streaming-consumer
  version: latest
  config:
    public:
      # communication via localhost because Qlever and consumer live in the same pod
      SPARQL_ENDPOINT: http://localhost:7001/sparql
      # Same stable kafka group as used in the init container
      KAFKA_GROUP: $(K8S_POD_NAMESPACE)-$(K8S_POD_NAME)
      BATCH_SIZE: 250
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 4Gi

health:
  image: repos/wikidata-platform/wdqs/wdqs-backend-health-monitor
  version: latest
  config:
    public:
      QUARKUS_REST_CLIENT_CONSUMER_URL: http://localhost:9101/metrics
      HEALTH_MONITOR_UPDATE_LAG_THRESHOLD: 10
      HEALTH_MONITOR_UPDATE_LAG_METRIC_NAME: wdqs_streaming_updater_update_lag_offset_Value
      HEALTH_MONITOR_INDEX_DIR: /srv/data/current
      HEALTH_MONITOR_INDEX_SPARQL_ENDPOINT: http://localhost:7001/sparql
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
  startup_probe:
    httpGet:
      path: /probe
      port: 8080
    # We allow 2h (720*10=7200s=2h) for the consumer to catch up to the current state
    failureThreshold: 720
    periodSeconds: 10
    # The consumer waits 10 seconds before exposing the metrics
    initialDelaySeconds: 10
  volumeMounts:
   - name: data-dir
     mountPath: /srv/data
     readOnly: true

proxy:
  image: repos/wikidata-platform/wdqs/wdqs-proxy
  version: latest
  service:
    port:
      name: http
      port: *proxyport
      targetPort: 8080
  config:
    public:
      QUARKUS_REST_CLIENT_DOWNSTREAM_SPARQL_ENDPOINT_URL: http://wdqs-main-internal-qlever:7001/sparql
      QUARKUS_REST_CLIENT_EVENTGATE_ENDPOINT_URL: http://eventgate-analytics.discovery.wmnet:4592
      QUERY_REWRITER_MW_SPARQL_ENABLED: false
      QUERY_REWRITER_FEDERATION_ENABLED: true
      QUERY_REWRITER_FEDERATION_ALLOWLIST_PATH: https://gitlab.wikimedia.org/repos/wikidata-platform/wdqs/wdqs-federation-allowlist/-/releases/permalink/latest/downloads/allowlist.json
      # Prefix for all service metrics. Not: the dot at the end of prefix is required by convention.
      WDQS_PROXY_METRICS_PREFIX: wdqs.proxy.
      # disable all metrics reporting by default. Toggle desired binders in helmfiles.
      QUARKUS_MICROMETER_ENABLED: false
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

# TODO: enable monitoring
monitoring:
  # If enabled is true, monitoring annotations will be added to the deployment.
  enabled: false

# only used in NOTES.txt
service:
  deployment: minikube

debug:
  enabled: false

mesh:
  enabled: true
  public_port: *proxyport
  upstream_local_port: 8080
  telemetry:
    port: 1667
  extra_service_selector_labels:
    component: proxy
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 500m
      memory: 500Mi

# Allow external traffic to reach this service via a (cluster provided) ingress controller.
# https://wikitech.wikimedia.org/wiki/Kubernetes/Ingress#Configuration_(for_service_owners)
ingress:
  enabled: false
  # By default, enabling ingress will switch the charts services from type NodePort to
  # ClusterIP. While that is fine for new services it may not be desired during transition
  # of existing ones from dedicated LVS to Ingress.
  # By setting keepNodePort to true, the services will stay of type NodePort.
  keepNodePort: false
  # gatewayHosts settings configure the hostnames this service will be reachable on.
  # By default, this will be a list like:
  # - {{ gatewayHosts.default }}.{{ domain }}
  # For all domains listed in .gatewayHosts.domains (specified by SRE for each environment)
  gatewayHosts:
    # default will expand to {{ .Release.Namespace }} as long as it is an empty string.
    default: ""
    # disableDefaultHosts may be set to true if the service should not be reachable via
    # the gateway hosts generated by default (see above).
    disableDefaultHosts: false
    # extraFQDNs is a list of extra FQDNs this service should be reachable on.
    # It can be used to extend the gateway hosts that are generated by default.
    extraFQDNs: []
  # If you want to attach routes of this release to an existing Gateway, provide the name
  # of that gateway here in the format: <namespace>/<gateway-name>
  # This is useful if you wish to make multiple releases available from the same hostname.
  existingGatewayName: ""
  # routeHosts is a list of FQDNs the httproutes should attach to.
  # If existingGatewayName not set, this list might be empty and will default to the gateway
  # host generated according to how .Values.gatewayHosts.* is configured.
  # If existingGatewayName is set, you need to provide the FQDNs your routes should attach to.
  routeHosts: []
  # HTTPRoute routing rules. By default https://<hosts from above>/ will be routed to
  # the service without modification.
  # Docs: https://istio.io/v1.9/docs/reference/config/networking/virtual-service/#HTTPRoute
  httproutes: []
  # Base CORS HTTP headers for the general use case.
  base_cors_policy: false
  # Add a custom CORS policy, injecting an Istio CorsPolicy config:
  # https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy
  # Takes precedence over base_cors_policy.
  custom_cors_policy: {}
  # Add a list of destination rule hosts to allow httproute rules to address more than 1 backend services.
  # NOTE: The list needs to be a list of kubernetes service DNS names
  destinationrulehosts: []

docker:
  registry: docker-registry.wikimedia.org
  pull_policy: IfNotPresent

resources:
  replicas: 1

networkpolicy:
  egress:
    enabled: false

# Add here the list of kafka-clusters (by name) that the service will need to reach.
kafka:
  allowed_clusters: []

affinity: {}

# The set of external services to allow egress to
# Example:
# kafka:
# - main-codfw
# - main-eqiad
# presto:
# - analytics
#
# See https://wikitech.wikimedia.org/wiki/Kubernetes/Deployment_Charts#Enabling_egress_to_services_external_to_Kubernetes
# for the list of supported services
external_services: {}

tolerations: []
