apiVersion: v2
description: Helm chart for the Push Notifications Service on WMF Kubernetes infrastructure
kubeVersion: ">=1.12"
name: push-notifications
version: 0.1.22
keywords:
  - mobile
  - push
  - notifications
  - Wikimedia
home: https://wikitech.wikimedia.org/wiki/Push_notifications
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/push-notifications/
team: https://wikitech.wikimedia.org/wiki/Content_Transform_Team
maintainers:
  - name: Yiannis Giannelos
    email: ygiannelos@wikimedia.org