apiVersion: v2
description: helm-state-metrics chart
name: helm-state-metrics
version: 0.2.2
appVersion: "v0.2.0"
keywords:
  - helm
  - prometheus-exporter
  - infrastructure
home: https://wikitech.wikimedia.org/wiki/Helm-state-metrics
sources:
  - https://gerrit.wikimedia.org/r/operations/software/helm-state-metrics
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: SRE Service Operations
    email: sre-service-ops@wikimedia.org
