opensearchCluster:
  general:
    serviceName: "opensearch-semantic-search-test"
    image: docker-registry.wikimedia.org/repos/data-engineering/opensearch:2026-08-03-124320-2498d27fa37e1bd707fab587a434169a611f66ed-production3@sha256:84c68ffd377c7fa26a9154dc47a5ab9fe24a7b0ab270ffe97126de61c4d5e407
    additionalConfig:
      # disable query insights metrics (https://github.com/opensearch-project/query-insights/issues/651)
      search.insights.top_queries.latency.enabled: "false"
      search.insights.top_queries.cpu.enabled: "false"
      search.insights.top_queries.memory.enabled: "false"
      search.insights.recommendations.enabled: "false"
  nodePools:
    - &node-pool-common
      component: data
      diskSize: "30Gi"
      persistence:
        pvc:
          storageClass: ceph-rbd-ssd
          accessModes:
            - ReadWriteOnce
      replicas: 1
      roles:
        - "data"
      resources:
        requests:
          memory: "4Gi"
          cpu: "2000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
      # These annotations enable/configure metrics scrapes
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9200"
        prometheus.io/path: "/_prometheus/metrics"
        prometheus.io/scheme: "https"
      # prevent pods from being scheduled on hosts with 1G networking
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: capabilities.nic
                operator: NotIn
                values:
                - 1G
    - <<: *node-pool-common
      component: masters
      replicas: 3
      roles:
        - "master"
        - "data"
      # prevent 2 masters from being scheduled on the same k8s worker
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: capabilities.nic
                operator: NotIn
                values:
                - 1G
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  opster.io/opensearch-cluster: opensearch-cluster
                  opster.io/opensearch-nodepool: masters
              topologyKey: kubernetes.io/hostname
certificate:
  extraFQDNs:
  - opensearch-semantic-search-test.discovery.wmnet

networkpolicy:
  egress:
    enabled: true
    dst_nets:
    - cidr: 10.2.2.63/32 # inference.svc.eqiad.wmnet
      ports:
      - protocol: tcp
        port: 30443
    - cidr: 10.2.1.63/32 # inference.svc.codfw.wmnet
      ports:
      - protocol: tcp
        port: 30443
