apiVersion: v2
description: A Helm chart for Kubernetes
name: kartotherian
version: 0.0.27
keywords:
  - maps
home: https://wikitech.wikimedia.org/wiki/Maps/v2
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/mediawiki/services/kartotherian
team: https://wikitech.wikimedia.org/wiki/Content_Transform_Team
maintainers:
  - name: Yiannis Giannelos
    email: ygiannelos@wikimedia.org
  - name: Luca Toscano
    email: ltoscano@wikimedia.org