apiVersion: v2
name: kserve-resources
version: 0.1.0
description: Helm chart for deploying kserve resources - Wikimedia LiftWing setup
type: application
keywords:
  - kserve
  - modelmesh
  - inference
  - machine-learning
  - model-serving
home: https://kserve.github.io/website/
sources:
  - https://github.com/kserve/kserve
maintainers:
  - name: Wikimedia Machine Learning Team
    url: https://www.mediawiki.org/wiki/Machine_Learning
annotations:
  category: AI/Machine Learning
  wmf/upstreamVersion: v1.17.0