# Default values for validating-admission-policies.

# In validationActions you may define overrides for the default
# validationActions field of a policy (which should be 'Deny').
# The key is the name of the policy, valid values are
# 'Deny', 'Warn', and 'Audit' (where 'Deny' and 'Warn' are mutually exclusive).
validationActions:
  disallow-probes-host: [Warn, Audit]
