# Over-ride values for the Python evaluator

main_app:
  image: repos/abstract-wiki/wikifunctions/function-evaluator/wasm-python3-all
  version: 2026-04-14-215402
  requests:
    cpu: 4
    memory: 800Mi
  limits:
    cpu: 6
    memory: 1Gi

mesh:
  certmanager:
    extraFQDNs:
    - 'wikifunctions-python-evaluator.discovery.wmnet'

config:
  public:
    # Set a nicer name for the OpenTelemetry entries than 'unknown_service'
    OTEL_SERVICE_NAME: wikifunctions-evaluator-python
    FUNCTION_EVALUATOR_TIMEOUT_MS: "9000"
    WASM_BINARY: /srv/service/programming-languages/rustpython.so
    PROGRAMMING_LANGUAGE_DIR: /srv/service/programming-languages
    WASMEDGE_HOME: /srv/service/programming-languages/wasmedge
    EXECUTOR_PROCESS_POOL_SIZE: "5"
    ENABLE_WASMEDGE_LIMITS: "0"
    WASMEDGE_GAS_LIMIT: "1000000"
    WASMEDGE_MEMORY_PAGE_LIMIT: "10000"
    WASMEDGE_TIMEOUT_MS: "11000"
    FUNCTION_EVALUATOR_WASI_ACQUIRE_TIMEOUT: "1500"
    createCustomSpans: true

# The evaluator's ingress config is peculiar since it is contained in
# "wikifunctions", that by default is used to create the gateway hosts
# value that Istio accepts. For example, the orchestrator responds
# to wikifunctions.discovery.wment (and its svc.{eqiad,codfw}.wmnet variants)
# and it cannot be shared by multiple Gateways.
# We explicitly discard the default and set new ones for the evaluators,
# that may be revisied once/if they get their own service status.
# Note: keep the gatewayHosts list in sync with the mesh's one.
ingress:
  enabled: true
  keepNodePort: true
  gatewayHosts:
    default: 'wikifunctions-python-evaluator'
