# Over-ride values for the Python evaluator

main_app:
  image: repos/abstract-wiki/wikifunctions/function-evaluator/rusty-py
  version: 2026-07-08-113600
  requests:
    cpu: 4
    memory: 800Mi
  limits:
    cpu: 6
    memory: 2Gi

mesh:
  certmanager:
    extraFQDNs:
    - 'wikifunctions-python-evaluator.discovery.wmnet'

config:
  public:
    # Set a nicer name for the OpenTelemetry entries than 'unknown_service'
    OTEL_SERVICE_NAME: wikifunctions-evaluator-python
    FUNCTION_EVALUATOR_TIMEOUT_MS: "9000"
    EXECUTOR_ROOT: /srv/executors
    EXECUTOR_PROCESS_POOL_SIZE: "5"
    WASMTIME_FUEL_LIMIT: "10000000000"
    WASMTIME_MEMORY_PAGES: "10000"
    MAX_REQUESTS_PER_ID: "100"

# The evaluator's ingress config is peculiar since it is contained in
# "wikifunctions", that by default is used to create the gateway hosts
# value that Istio accepts. For example, the orchestrator responds
# to wikifunctions.discovery.wmnet (and its svc.{eqiad,codfw}.wmnet variants)
# and it cannot be shared by multiple Gateways.
# We explicitly discard the default and set new ones for the evaluators,
# that may be revisied once/if they get their own service status.
# Note: keep the gatewayHosts list in sync with the mesh's one.
ingress:
  enabled: true
  keepNodePort: true
  gatewayHosts:
    default: 'wikifunctions-python-evaluator'
