cache:
  mcrouter:
    enabled: true
    route_prefix: local/wf
    zone: codfw
    routes:
      - route: /local/wf
        pool: wf-codfw
        modifykey:
          prefix: "wforch:"
        # No failover for wikifunction
        failover_time: 0
      - route: /codfw/wf-wan
        pool: wf-codfw
        modifykey:
          prefix: "wforch:"
        failover_time: 0
        replica:
          route: /eqiad/wf-wan
          pool: wf-eqiad
