resources:
  replicas: 1

main_app:
  requests:
    cpu: 1
    memory: 200Mi
  limits:
    cpu: 1
    memory: 1Gi

mesh:
  certmanager:
    extraFQDNs:
    - 'wikifunctions-javascript-evaluator.k8s-staging.discovery.wmnet'

config:
  public:
    ORCHESTRATOR_CALLBACK_API_URI: 'https://wikifunctions.k8s-staging.discovery.wmnet:30443/1/v1/callback/'
