# Over-ride values for the JavaScript evaluator

main_app:
  image: repos/abstract-wiki/wikifunctions/function-evaluator/rusty-js
  version: 2026-06-03-023342
  requests:
    cpu: 4
    memory: 800Mi
  limits:
    cpu: 6
    memory: 1Gi

config:
  public:
    # Set a nicer name for the OpenTelemetry entries than 'unknown_service'
    OTEL_SERVICE_NAME: wikifunctions-evaluator-rust-javascript
    FUNCTION_EVALUATOR_TIMEOUT_MS: "9000"
    JAVASCRIPT_INTERPRETER_FILE: /srv/rustversion/interpreters/wasip1_quickjs_uncompiled_spliced.wasm
    EXECUTOR_ROOT: /srv/executors
    PROGRAMMING_LANGUAGE_DIR: /srv/rustversion/interpreters/
    EXECUTOR_PROCESS_POOL_SIZE: "5"
    WASMTIME_FUEL_LIMIT: "10000000000"
    WASMTIME_MEMORY_PAGES: "10000"
    MAX_REQUESTS_PER_ID: "100"

