resources:
  replicas: 1

main_app:
  requests:
    cpu: 1
    memory: 200Mi
  limits:
    cpu: 1
    memory: 1Gi

discovery:
  listeners:
    - mw-wikifunctions-ro
    - wikifunctions-javascript-evaluator-staging
    - wikifunctions-python-evaluator-staging

config:
  public:
    ORCHESTRATOR_CONFIG: |
      {
        "addNestedMetadata": false,
        "createCustomSpans": true,
        "generateFunctionsMetrics": true,
        "maxSimultaneousExecutions": 1000,
        "useWikidata": true,
        "wikidataImport": {
          "qualifiers": true,
          "references": false
        },
        "memcachedUri": "127.0.0.1:11213",
        "maxRecursionDepth": 1000,
        "useMemcached": true,
        "useWikidataMemcached": true,
        "wikidataMemcachedTTL": 86400,
        "useBatching": true,
        "evaluatorConfigs": [
          {
            "programmingLanguages": ["Z610"],
            "evaluatorUri": "http://localhost:6512/1/v1/evaluate/",
            "evaluatorWs": "",
            "useReentrance": false
          },
          {
            "programmingLanguages": ["Z600"],
            "evaluatorUri": "http://localhost:6513/1/v1/evaluate/",
            "evaluatorWs": "",
            "useReentrance": false
          }
        ]
      }
