apiVersion: v2
description: A Helm chart for Kubernetes
kubeVersion: ">=1.8"
name: wikifeeds
version: 0.2.6
keywords:
  - REST
  - API
  - node service
  - mobile apps
  - MediaWiki
  - Wikipedia
  - extension
home: https://wikitech.wikimedia.org/wiki/Wikifeeds
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/wikifeeds/
team: https://wikitech.wikimedia.org/wiki/Content_Transform_Team
maintainers:
  - name: Yiannis Giannelos
    email: ygiannelos@wikimedia.org
  - name: Dmitry Brant
    email: dbrant@wikimedia.org
