qlever:
  config:
    public:
      QLEVER_MAX_MEM: 30G
      QLEVER_MAX_CACHE: 8G
      QLEVER_NUM_QUERIES: 10
  requests:
    cpu: 5
    memory: 35Gi
  limits:
    cpu: 5
    memory: 35Gi

# Matches the QLEVER_NUM_QUERIES override above.
proxy:
  config:
    public:
      QUARKUS_REST_CLIENT_DOWNSTREAM_SPARQL_ENDPOINT_CONNECTION_POOL_SIZE: 10
