app:
  version: &base-image-version airflow-3.3.1-py3.11-2026-08-17-132624-cb7bea2af5eb4f962449b6d162518c19ca70547f@sha256:61ebd3f988933724d441c3ec2d1c3f31c0ca36b4818b39910e74c0d6b079b59b
  executor_pod_image_version: *base-image-version
  waitForMigrations: true
  args: ["api-server", "--pid" , "/tmp/airflow-webserver.pid"]
  readiness_probe:
    httpGet:
      path: /api/v2/monitor/health

dagProcessor:
  enabled: true

config:
  airflow:
    config:
      scheduler:
        standalone_dag_processor: true
