{{- if or .Values.global.datahub.systemUpdate.enabled .Values.datahubUpgrade.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "base.name.release" . }}-secret-config
  labels:
    app: {{ template "base.name.chart" . }}
    chart: {{ template "base.name.chartid" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This secret is declared as a pre-install hook, in order that the setup and upgrade
    # jobs can make use of its contents.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
type: Opaque
{{- if .Values.datahub_config.private }}
data: {{- range $k := (keys .Values.datahub_config.private | sortAlpha) }}
  {{ $k }}: {{ get $.Values.datahub_config.private $k | b64enc | quote }}
{{- end -}}
{{- end -}}
{{- end }}