apiVersion: v2
appVersion: 1.53.0
description: A Jaeger Helm chart for Kubernetes
kubeVersion: ">= 1.21-0"
name: jaeger
type: application
version: 3.1.2
# CronJobs require v1.21
keywords:
  - jaeger
  - opentracing
  - tracing
  - instrumentation
  - infrastructure
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
home: https://wikitech.wikimedia.org/wiki/Jaeger
sources:
  - https://hub.docker.com/u/jaegertracing/
  - https://gerrit.wikimedia.org/r/admin/repos/operations/docker-images/production-images
team: https://wikitech.wikimedia.org/wiki/SRE/Infrastructure_Foundations
maintainers:
  - name: SRE Infrastructure Foundations
    email: sre-infra-foundations@wikimedia.org
  - name: Chris Danis
    email: cdanis@wikimedia.org
