apiVersion: v2
description: A generic helm chart for AQS HTTP gateway applications
name: aqs-http-gateway
version: 0.0.16
home: https://wikitech.wikimedia.org/wiki/Data_Platform/Systems/AQS
sources:
  - https://gerrit.wikimedia.org/g/analytics/aqs
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering/Data_Engineering
maintainers:
  - name: Balthazar Rouberol
    email: brouberol@wikimedia.org
  - name: Ben Tullis
    email: btullis@wikimedia.org