opensearchCluster:
  general:
    serviceName: "opensearch-semantic-search"
    image: docker-registry.wikimedia.org/repos/data-engineering/opensearch:3@sha256:95eea5d5bbd6ca958f53e120abe631b2e6f99c234339093627216a8fb34f217f
  nodePools:
    - &node-pool-common
      component: data
      diskSize: "170Gi"
      persistence:
        pvc:
          storageClass: ceph-rbd-ssd
          accessModes:
            - ReadWriteOnce
      replicas: 9
      env:
        - name: LD_LIBRARY_PATH
          value: /usr/share/opensearch/plugins/opensearch-knn/lib
      jvm: -Xmx6G -Xms6G -Djava.library.path=/usr/share/opensearch/plugins/opensearch-knn/lib
      roles:
        - "data"
      resources:
        requests:
          memory: "38Gi"
          cpu: "4000m"
        limits:
          memory: "38Gi"
          cpu: "4000m"
    # These annotations enable/configure metrics scrapes
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9200"
        prometheus.io/path: "/_prometheus/metrics"
        prometheus.io/scheme: "https"
      # prevent nodes from being scheduled on hosts with 1g networking
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: capabilities.nic
                operator: NotIn
                values:
                - 1G
    - <<: *node-pool-common
      component: masters
      roles:
        - "master"
        - "data"
      replicas: 7
      # prevent nodes from being scheduled on hosts with 1g networking
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: capabilities.nic
                operator: NotIn
                values:
                - 1G
      # prevent 2 masters from being scheduled on the same k8s worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  opster.io/opensearch-cluster: opensearch-cluster
                  opster.io/opensearch-nodepool: masters
              topologyKey: kubernetes.io/hostname
certificate:
  extraFQDNs:
  - opensearch-semantic-search.discovery.wmnet

networkpolicy:
  egress:
    enabled: true
    dst_nets:
    - cidr: 10.2.2.63/32 # inference.svc.eqiad.wmnet
      ports:
      - protocol: tcp
        port: 30443
    - cidr: 10.2.1.63/32 # inference.svc.codfw.wmnet
      ports:
      - protocol: tcp
        port: 30443
    - cidr: 10.64.32.100/32 # relforge1008.eqiad.wmnet, for testing
      ports:
      - protocol: tcp
        port: 8003
