main_app:
  version: 2026-10-08-120657-production

resources:
  replicas: 2

service:
  deployment: production

ingress:
  enabled: true
  gatewayHosts:
    extraFQDNs:
      - developer.wikimedia.org

mesh:
  enabled: true
  public_port: 4016
