apiVersion: v2
description: A Helm chart for eventrouter (https://github.com/heptiolabs/eventrouter)
name: eventrouter
version: 0.4.4
appVersion: "0.4"
keywords:
  - eventrouter
# Looking for replacement: https://phabricator.wikimedia.org/T343787
home: https://wikitech.wikimedia.org/wiki/Kubernetes/Clusters/New#Eventrouter
sources:
  - https://github.com/heptiolabs/eventrouter
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/software/heptiolabs/eventrouter/
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: Janis Mayboom
    email:  jmeybohm@wikimedia.org
