# The list of namespaces in which cloudnative-pg clusters are deployed.
# If you plan to deploy a cluster to a new namespace, you'll need to add it in there
# (please keep the list sorted, and keep the cloudative-pg-operator first) and apply admin_ng
watchedNamespaces:
- cloudnative-pg-operator
- airflow-analytics-product
- airflow-analytics-test
- airflow-dev
- airflow-fr-tech
- airflow-main
- airflow-ml
- airflow-platform-eng
- airflow-research
- airflow-search
- airflow-sre
- airflow-test-k8s
- airflow-wikidata
- airflow-wmde
- growthbook
- growthbook-next
