# List of namespaces that the flink-operator will watch and be granted permissions to manage.
# If you plan to deploy a flink app to a new namespace, add it to the list (please keep it sorted)
# and redeploy admin_ng
watchNamespaces:
- mw-content-history-reconcile-enrich
- mw-content-history-reconcile-enrich-next
- mw-page-html-content-change-enrich
- mw-page-html-content-change-enrich-next
- mw-page-html-feature-counts-change-enrich
- mw-page-html-feature-counts-change-enrich-next
- webrequest-page-view
- webrequest-page-view-next

# Allow the flink-kubernetes-operator chart to create RBAC resources in watchNamespaces.
rbac:
  create: true

zookeeper:
  allowed_clusters:
    - flink-eqiad
