manager:
  watchNamespace:
  - opensearch-test
  - opensearch-ipoid-test
  - opensearch-ipoid
  - opensearch-semantic-search
  - opensearch-semantic-search-test
  - opensearch-toolhub
  - opensearch-toolhub-test
  - opensearch-apifeatureusage
  - opensearch-apifeatureusage-test
  - opensearch-ttmserver
  - opensearch-ttmserver-test