config:
  airflow:
    instance_name: wmde

ingress:
  gatewayHosts:
    default: "airflow-wmde"
    extraFQDNs:
    - airflow-wmde.wikimedia.org

worker:
  proxy:
    urldownloader:
      enabled: true

external_services:
  task-pod:
    dumps: [wikimedia]
