apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: disallow-host-process
spec:
  namespaceTemplate:
    metadata:
      labels:
        pod-security.wmf.org/profile: baseline
  steps:
  - name: step-01_prepare_host-process-containers
    try:
    - apply:
        file: ../disallow-host-process-containers.yaml
  - name: step-02
    try:
    - apply:
        file: pod-good.yaml
    - apply:
        file: pod-bad.yaml
        expect:
        - check:
            ($error != null): true
