apiVersion: v2
description: A Helm chart for the Link Recommendation Service on WMF Kubernetes.
kubeVersion: ">=1.12"
name: linkrecommendation
version: 0.2.27
home: https://wikitech.wikimedia.org/wiki/Add_Link
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/research/mwaddlink/
team: https://wikitech.wikimedia.org/wiki/Growth
maintainers:
  - name: Martin Urbanec
    email: murbanec@wikimedia.org
