apiVersion: v2
description: envoyproxy ratelimiter with nutcracker and statsd exporter
name: ratelimit
version: 0.0.5
keywords:
  - ratelimit
  - envoy
  - infrastructure
home: https://wikitech.wikimedia.org/wiki/Ratelimit
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/operations/docker-images/production-images
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: SRE Service Operations
    email: sre-service-ops@wikimedia.org
