config:
  turnilo:
    url: https://turnilo.wikimedia.org

auth_proxy:
  httpd_cas:
    site:
      server_name: turnilo.wikimedia.org
      cas_root_proxied_as: https://turnilo.wikimedia.org

external_services:
  cas: [ idp ]

ingress:
  gatewayHosts:
    default: "turnilo"
    extraFQDNs:
    - turnilo.wikimedia.org