apiVersion: v2
name: function-orchestrator
version: 0.3.25
description: A Helm chart for running the Wikifunctions orchestrator back-end services on Kubernetes
kubeVersion: ">=1.31"
keywords:
 - wikifunctions
 - abstract-wikipedia
home: https://wikitech.wikimedia.org/wiki/Wikifunctions
sources:
 - https://gitlab.wikimedia.org/repos/abstract-wiki/wikifunctions/function-orchestrator
maintainers:
  - name: James Forrester
    email: jforrester@wikimedia.org
  - name: Cory Massaro
    email: cmassaro@wikimedia.org
team: https://wikitech.wikimedia.org/wiki/Wikifunctions
