apiVersion: v2
name: knative-serving-crds
description: Knative Serving Custom Resource Definitions
type: application
version: 0.2.1
appVersion: v1.21.1
annotations:
  skip-checks: "team,maintainers,home,sources"