helmDefaults:
  createNamespace: false
  verify: false
  atomic: true
  timeout: 600
  force: false
  args:
    - --kubeconfig
    - {{ .Environment.Values | get "kubeConfig" (printf "/etc/kubernetes/liftwing-studio-deploy-%s.config" .Environment.Name) }}

environments:
  dse-k8s-eqiad:
    values:
      - releases: [production]
      - "/etc/helmfile-defaults/clusterinfo-{{ .Environment.Name }}.yaml"
    missingFileHandler: Warn

---

templates:
  default: &default
    chart: wmf-stable/liftwing-studio
    recreatePods: {{ if (hasKey .Environment.Values "roll_restart") }}{{ eq .Environment.Values.roll_restart "1" }}{{ else }}false{{end}}
    installedTemplate: '{{`{{ if hasKey .Environment.Values "releases" }}{{ has .Release.Name .Environment.Values.releases }}{{ else }}{{ "no releases defined for this environment" | fail }}{{end}}`}}'
    missingFileHandler: Warn
    values:
      - "/etc/helmfile-defaults/general-{{ .Environment.Name }}.yaml"
      - "values.yaml"
      - "/etc/helmfile-defaults/private/dse-k8s_services/liftwing-studio/{{ .Environment.Name }}.yaml"
      - "values-{{ .Environment.Name }}.yaml"
      - "values-{{`{{ .Release.Name }}`}}.yaml"
      - environmentName: "{{ .Environment.Name }}"

bases:
  - ../global.yaml

hooks:
  - events: ["prepare"]
    command: "helmfile_log_sal"
    args:
      [
        "{{`{{.HelmfileCommand}}`}}",
        "[{{`{{ .Environment.Name }}`}}] START helmfile.d/dse-k8s-services/liftwing-studio: {{`{{.HelmfileCommand}}`}}",
      ]
  - events: ["cleanup"]
    command: "helmfile_log_sal"
    args:
      [
        "{{`{{.HelmfileCommand}}`}}",
        "[{{`{{ .Environment.Name }}`}}] DONE helmfile.d/dse-k8s-services/liftwing-studio: {{`{{.HelmfileCommand}}`}}",
      ]

releases:
  - name: production
    namespace: liftwing-studio
    <<: *default
