app:
  # ratelimit configuration
  # see https://github.com/envoyproxy/ratelimit/tree/main#configuration
  # Array keys are ratelimit domains (they need to be unique), the value
  # needs is one or many descriptors.
  configuration:
    mw-api-int:
      - key: user-agent
        rate_limit:
          unit: second
          requests_per_unit: 1000
monitoring:
  statsd:
    # Override default statsd config file from chart with inline yaml config
    filename: ~
    config: |-
      ---
      mappings:
        # Limit metrics ##############################################################
        # Mappings for internal rate limiting
        - match: "ratelimit\\.service\\.rate_limit\\.(.*)\\.(.*)\\.(.*)"
          match_type: regex
          name: "ratelimit_service_$3"
          labels:
            domain: "$1"
            key1: "$2" # Old label for backwards-compatibility
            policy: "default" # Hardcode because we don't use policies here
            user_class: "$2" # Consider the rate-limit key as the user_class. It's not right, but we need some uniformity in labels so we can build dashboards.
        # Service metrics ##############################################################
        - match: "ratelimit.service.call.should_rate_limit.*"
          name: "ratelimit_service_should_rate_limit_error"
          match_metric_type: counter
          labels:
            err_type: "$1"
        - match: "ratelimit_server.*.total_requests"
          name: "ratelimit_service_total_requests"
          match_metric_type: counter
          labels:
            grpc_method: "$1"
        - match: "ratelimit_server.*.response_time"
          name: "ratelimit_service_response_time_seconds"
          timer_type: histogram
          labels:
            grpc_method: "$1"
        - match: "ratelimit.service.config_load_success"
          name: "ratelimit_service_config_load_success"
          match_metric_type: counter
        - match: "ratelimit.service.config_load_error"
          name: "ratelimit_service_config_load_error"
          match_metric_type: counter
        # Drop everything else
        - match: "."
          match_type: "regex"
          action: "drop"
          name: "dropped"
