resources:
  replicas: 11 # Start with 1 ratelimit pod per ms-fe
nutcracker:
  limits:
    memory: 400Mi
ingress:
  enabled: true
  gatewayHosts:
    default: "ratelimit-media"
app:
  # ratelimit configuration
  # see https://github.com/envoyproxy/ratelimit/tree/main#configuration
  # Array keys are ratelimit domains (they need to be unique), the value
  # needs is one or many descriptors.
  #
  #
  # This dummy (but should be valid) config sets limits for two policies,
  # originals and thumbnails (to be defined at the route level in envoy config)
  # The user_class should be set in envoy based on the values of X-Trusted-Request and X-Is-Browser
  # We only define anon for now
  # The user_id should be X-Client-Ip
  #
  # This limits to:
  #   5MB of total BYTES_SENT per second **FIXED WINDOW** on originals
  #   10MB of total BYTES_SENT per second **FIXED WINDOW** on thumbnails
  #
  # The tally is done at the end of the request, so a single request exceeding the quota would go
  # through, but the next one would not.
  configuration:
    upload:
      - key: policy
        value: originals
        descriptors:
          - key: user_class
            value: anon
            descriptors:
              - key: user_id
                rate_limit:
                  unit: second
                  requests_per_unit: 5000000
                shadow_mode: true
      - key: policy
        value: thumbnails
        descriptors:
          - key: user_class
            value: anon
            descriptors:
              - key: user_id
                rate_limit:
                  unit: second
                  requests_per_unit: 10000000
                shadow_mode: true
config:
  cache_key_prefix: "media_"
# TODO metrics config

monitoring:
  statsd:
    # Override default statsd config file from chart with inline yaml config
    filename: ~
    config: |-
      ---
      mappings:
        # Limit metrics ##############################################################
        # Mappings for media rate limiting
        - match: "ratelimit\\.service\\.rate_limit\\.upload\\.policy_(.*)\\.user_class_(.*)\\.user_id\\.(.*)"
          match_type: regex
          name: "ratelimit_service_media_$3"
          labels:
            policy: "$1"
            user_class: "$2"
        # Service metrics ##############################################################
        - match: "ratelimit.service.call.should_rate_limit.*"
          name: "ratelimit_service_should_rate_limit_error"
          match_metric_type: counter
          labels:
            err_type: "$1"
        - match: "ratelimit_server.*.total_requests"
          name: "ratelimit_service_total_requests"
          match_metric_type: counter
          labels:
            grpc_method: "$1"
        - match: "ratelimit_server.*.response_time"
          name: "ratelimit_service_response_time_seconds"
          timer_type: histogram
          labels:
            grpc_method: "$1"
        - match: "ratelimit.service.config_load_success"
          name: "ratelimit_service_config_load_success"
          match_metric_type: counter
        - match: "ratelimit.service.config_load_error"
          name: "ratelimit_service_config_load_error"
          match_metric_type: counter
        # Drop everything else
        - match: "."
          match_type: "regex"
          action: "drop"
          name: "dropped"
