{{- define "ratelimit.config" }}
---
domain: wikimedia
descriptors:
{{- if .Values.main_app.ratelimiter.enabled }}
  # NOTE: when changing the descriptor structure,
  #       also update the matcher rules in ratelimiter_metrics.yaml!
  {{/* Inject a DENY policy that consists of just the "*" class with a limit of 0 per minute. */}}
  {{- $deny_unit := .Values.main_app.ratelimiter.units | first }}
  {{- $deny_policy := dict "limits" (dict "*" (dict $deny_unit 0)) }}
  {{- $policies := mustMerge $.Values.main_app.ratelimiter.policies (dict "DENY" $deny_policy) }}
  {{- range $name, $policy := $policies }}
  # Rate limit policies for use by the REST gateway.
  # A policy defines the limits for each rate limit class.
  - key: policy
    value: {{ $name }}
    descriptors:
      # For a description of the available rate limit classes and their meaning and purpose,
      # see the comment on the wmf_ratelimit_info method in restgw_ratelimits.lua.
      {{/* Inject a DENY class that has a limit of 0 per minute (could be any time unit, doesn't matter). */}}
      {{- $limits := mustMerge $policy.limits (dict "DENY" (dict $deny_unit 0)) }}
      {{- range $class, $units := $limits }}
      - key: user_class
        {{- if ne $class "*" }}
        value: {{ $class }}
        {{- else}}
        # Fallback for unknown classes.
        # TODO: set value_to_metrics: true
        # See https://github.com/envoyproxy/ratelimit/pull/996
        # Adjust ratelimiter_metrics.yaml accordingly.
        {{- end }}
        descriptors:
          - key: user_id
            descriptors:
              {{- range $unit, $req := $units }}
              - key: unit
                value: {{ $unit }}
                rate_limit:
                  requests_per_unit: {{ int $req }}
                  unit: {{ $unit }}
                {{- if ( $policy.shadow_mode | default false ) }}
                shadow_mode: true
                {{- end }}
              {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
