main_app:
  jwt:
    enabled: true
    issuer: "foobar"
  jwks:
    kid: "12345"
    key: "54321"

  rest_gateway_routes:
    - name: main_services
      timeout: 120s
      urls:
        - name: foo_bar
          in: 'main/foo/bar/(.+)'
          out: '/foo/bar/\2'
