mesh:
  enabled: true
  certs:
    cert: |-
      -- begin --
      12345
      -- end --
    key: |-
      -- begin --
      678910
      -- end --

main_app:
  rest_gateway_routes:
    - name: main_services
      timeout: 120s
      urls:
        - name: foo_bar
          in: 'main/foo/bar/(.+)'
          out: '/foo/bar/\2'
