config:
  wikimedia_enterprise:
    username: me
    password: secret
  opensearch_semantic_search_eqiad:
    username: semantic@eqiad
    password: secret-semantic@eqiad
  opensearch_semantic_search_codfw:
    username: semantic@codfw
    password: secret-semantic@codfw
