# We currently run a non-official release, which was built on a
# specific commit, to include a bugfix we care about
# (https://github.com/growthbook/growthbook/pull/5520)
image: &app_image repos/data-engineering/growthbook/next
version: &app_version 2026-04-13-070438-992ed9c24cd73e41d6534b54475664722b02c267@sha256:d471b89576c42d34f75445cbefba37c9f17f86252635b60cd2b6a8bd4231312a
app_origin: &app_origin https://growthbook.wikimedia.org
api_host: &api_host https://growthbook-api.wikimedia.org

growthbook-backend:
  app:
    image: *app_image
    version: *app_version

  config:
    public: # See https://docs.growthbook.io/self-host/env
      APP_ORIGIN: *app_origin
      API_HOST: *api_host
      EMAIL_FROM: "growthbook@wikimedia.org"
    oidc:
      clientId: growthbook

  external_services:
    presto: [analytics]
    cas: [idp]

  ingress:
    gatewayHosts:
      default: "growthbook-api"
      extraFQDNs:
      - growthbook-api.wikimedia.org

growthbook-frontend:
  app:
    image: *app_image
    version:  *app_version

  config:
    public: # See https://docs.growthbook.io/self-host/env
      APP_ORIGIN: *app_origin
      API_HOST: *api_host

  ingress:
    gatewayHosts:
      default: "growthbook"
      extraFQDNs:
      - growthbook.wikimedia.org
