# We currently run a non-official release, which was built on a
# specific commit, to include a bugfix we care about
# (https://github.com/growthbook/growthbook/pull/5520)
image: &app_image repos/data-engineering/growthbook
version: &app_version 4.4.0-2026-06-02-203128-d7731180fca469d0eda2ebda52438164dbffbada
app_origin: &app_origin https://growthbook.wikimedia.org
api_host: &api_host https://growthbook-api.wikimedia.org

growthbook-backend:
  app:
    image: *app_image
    version: *app_version

  config:
    public: # See https://docs.growthbook.io/self-host/env
      APP_ORIGIN: *app_origin
      API_HOST: *api_host
      EMAIL_FROM: "growthbook@wikimedia.org"
    oidc:
      clientId: growthbook

  external_services:
    presto: [analytics]
    cas: [idp]

  ingress:
    gatewayHosts:
      default: "growthbook-api"
      extraFQDNs:
      - growthbook-api.wikimedia.org

growthbook-frontend:
  app:
    image: *app_image
    version:  *app_version

  config:
    public: # See https://docs.growthbook.io/self-host/env
      APP_ORIGIN: *app_origin
      API_HOST: *api_host

  ingress:
    gatewayHosts:
      default: "growthbook"
      extraFQDNs:
      - growthbook.wikimedia.org
