# WMF staging main release specific values.

app:
  # These are set in common values.yaml file.
  # Change them here if you need to override them for the staging release.
  #
  # version: v1.50.0
  # logConfiguration:
  #   rootLogger.level: INFO

  taskManager:
    replicas: 2
    resource:
      cpu: 2
      memory: 6000m

  config_files:
    app.config.yaml:

      # Configs for eventutilities python stream_manager.
      stream_manager:
        job_name: mw-page-html-content-change-enrich-next

        # Don't use async process function.
        # This avoids the use of a ThreadPoolExecutor
        # For async minibatch execution.
        # This is a trial for the following tasks.
        # See: https://phabricator.wikimedia.org/T422928
        # See: https://phabricator.wikimedia.org/T421216#11809025
        process_async_enabled_default: false

        # Configure sources and sinks.
        source:
          stream: mediawiki.page_change.v1:1.3.0
          # source parallelism shoudl probably be set to the number of input Kafka topic-partitions.
          # mediawiki.page_change.v1 is made up of two topics, each of one partition
          # (as of 2026-04)
          parallelism: 2
          options:
            # OTTO: temporarily use staging release to tune and test backfilling.
            #       allowing the production release to always consume from latest
            #       (missing messages) after restarts.
            #       Note that the topic prefixes we produce to are 'staging.', so we
            #       won't collied with the 'production' 'eqiad.' prefixed topics.
            #       https://phabricator.wikimedia.org/T421216
            # TODO: reset this to jumbo-eqiad before we productionize.
            #bootstrap_servers: kafka-test-eqiad.external-services.svc.cluster.local:9093
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            # Kafka consumer group naming follows convention: <job_name>__<k8s_cluster_name>
            consumer_group: mw-page-html-content-change-enrich-next__dse-k8s-eqiad.001

        sink:
          stream: mediawiki.page_html_content_change.dev5:1.0.0
          options:
            # OTTO: See note above.
            # TODO: reset this to jumbo-eqiad before we productionize.
            #bootstrap_servers: kafka-test-eqiad.external-services.svc.cluster.local:9093
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            # Prefix the output topic with 'staging.' for the staging release output.
            # this allows us to use Kafka jumbo-eqiad for backfill testing if we need to,
            # without potentiall affecting the production release output topics.
            kafka_topic_prefix: staging.

        error_sink:
          stream: mw_page_html_content_change_enrich.error:2.1.0
          options:
            # OTTO: See note above.
            # TODO: reset this to jumbo-eqiad before we productionize.
            #bootstrap_servers: kafka-test-eqiad.external-services.svc.cluster.local:9093
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            # Prefix the error topic with 'staging.' for the staging release output.
            # this allows us to use Kafka jumbo-eqiad for backfill testing if we need to,
            # without potentiall affecting the production release output topics.
            kafka_topic_prefix: staging.


  job:
    # TODO: we might consider setting
    # kubernetes.operator.job.upgrade.last-state.max.allowed.checkpoint.age.
    # to fallback on savepoints if checkpoints are too old.
    # This might require changing checkpoint retention policy.
    upgradeMode: last-state


  flinkConfiguration:
    # Set the staging release specific HA storageDir path.
    # Note: Naming convention is different than in mw-page-content-change-enrich-next due to swift template in flink chart
    "high-availability.storageDir": "s3://mw-page-html-content-change-enrich-next.dse-k8s-eqiad/staging/high-availability"

flink:
  object_store:
    # Set the staging release specific objectstore bucket
    swift_bucket: mw-page-html-content-change-enrich-next.dse-k8s-eqiad

external_services:
  # OTTO: See note above.
  #kafka:  [test-eqiad]
  kafka:  [jumbo-eqiad]

