{{- /* WMF: upstream removed this template when it dropped PodSecurityPolicy
       support. We keep it to bind the per tenant namespace Roles created by
       nodeplugin-role.yaml. */}}
{{- if .Values.rbac.create }}
{{ range $tenantNamespace := $.Values.tenantNamespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ceph-csi-rbd.nodeplugin.fullname" $ }}-tenant
  namespace: {{ $tenantNamespace }}
  labels:
    app: {{ include "ceph-csi-rbd.name" $ }}
    chart: {{ include "ceph-csi-rbd.chart" $ }}
    component: {{ $.Values.nodeplugin.name }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    {{- with $.Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ceph-csi-rbd.serviceAccountName.nodeplugin" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ceph-csi-rbd.nodeplugin.fullname" $ }}-tenant
  apiGroup: rbac.authorization.k8s.io

{{- end -}}
{{- end -}}
