issuers:
  discovery:
    profile: k8s_wikikube
    # In case of fire, you can use pki2003
    url: https://pki2002.codfw.wmnet:8443

resources:
  requests:
    memory: 500Mi
  limits:
    memory: 1Gi