apiVersion: v2
description: A Helm chart for the Envoy-based API Gateway
kubeVersion: ">=1.23"
name: api-gateway
version: 0.15.8 # exempt userinfo%7Ctokens
keywords:
  - rest-gateway
  - api-gateway
  - envoy
home: https://wikitech.wikimedia.org/wiki/REST_Gateway
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/software/envoyproxy/ratelimiter/
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/
team: https://wikitech.wikimedia.org/wiki/MediaWiki_Interfaces_Team
maintainers:
  - name: Daniel Kinzler
    email: dkinzler@wikimedia.org
  - name: Clément Goubert
    email: cgoubert@wikimedia.org
