shellbox:
  flavour: icu72

service:
  # Use ClusterIP, which is fine for the temporary use case.
  nodePort: false
  # The templating doesn't let us statically allocate an IP address, but
  # whatever gets allocated should be stable across deploys.

mesh:
  public_port: 4081
  # Override local cluster name (defaults to namespace) to disambiguate in
  # tracing and envoy metrics.
  tracing:
    service_name: shellbox-icu72

# No idea, putting 4 as a start
resources:
  replicas: 4
