shellbox:
  flavour: score83

service:
  deployment: production

main_app:
  requests:
    cpu: 1
  limits:
    cpu: 8  # lilypond v2.24 is a _lot_ more CPU hungry

mesh:
  enabled: true
  public_port: 4008
  tracing:
    enabled: true
    sampling: 10
  envoy_stats_config:
    # Override histogram buckets as these requests tend to be longer
    histogram_bucket_settings:
      # let rq_time fall through to the default buckets, as they are big enough
      # the rest is a copy of the default buckets from the mesh template
      - match:
          safe_regex:
            regex: ".+upstream_cx_connect_ms$"
        buckets: [
          1,
          5,
          10,
          25,
          50,
          100,
          250,
          500,
          1000
        ]
      - match:
          safe_regex:
            regex: ".+(upstream|downstream)_cx_length_ms$"
        buckets: [
          2500,
          5000,
          10000,
          30000,
          60000,
          300000
        ]
      # remove 0.5, 1 and > 60000 default buckets
      - match:
          safe_regex:
            regex: ".+"
        buckets: [
          5,
          10,
          25,
          50,
          100,
          250,
          500,
          1000,
          2500,
          5000,
          10000,
          30000,
          60000
        ]

resources:
  replicas: 8

config:
  public:
   FPM__log_level: debug
