proxy:
  config:
    public:
      QUARKUS_REST_CLIENT_DOWNSTREAM_SPARQL_ENDPOINT_URL: http://wdqs-main-internal-qlever:7001/sparql

ingress:
  gatewayHosts:
    default: wdqs2-main-internal

mesh:
  certmanager:
    default_host: wdqs2-main-internal

qlever:
  config:
    public:
      QLEVER_DBNAME: wikidata_main
      QLEVER_MAX_MEM: 100G
      QLEVER_MAX_CACHE: 32G
  requests:
    cpu: 4
    memory: 32Gi
  limits:
    cpu: 10
    memory: 100Gi

init:
  config:
    public:
      NEW_INDEX_S3_BUCKET: wdqs-update-pipeline
      NEW_INDEX_S3_PATH: wikidata_main/
