proxy:
  config:
    public:
      QUARKUS_REST_CLIENT_DOWNSTREAM_SPARQL_ENDPOINT_URL: http://wdqs-scholarly-internal-qlever:7001/sparql

ingress:
  gatewayHosts:
    default: wdqs2-scholarly-internal
