proxy:
  config:
    public:
      QUARKUS_REST_CLIENT_DOWNSTREAM_SPARQL_ENDPOINT_URL: http://wdqs-scholarly-external-qlever:7001/sparql

ingress:
  gatewayHosts:
    default: wdqs2-scholarly-external
    extraFQDNs:
    - query-scholarly-next.wikidata.org

mesh:
  certmanager:
    default_host: wdqs2-scholarly-external

qlever:
  config:
    public:
      QLEVER_DBNAME: scholarly_articles
      QLEVER_MAX_MEM: 20G
      QLEVER_MAX_CACHE: 8G
  requests:
    memory: 8Gi
  limits:
    memory: 24Gi

init:
  config:
    public:
      NEW_INDEX_S3_BUCKET: wdqs-update-pipeline
      NEW_INDEX_S3_PATH: scholarly_articles/
