apiVersion: v2
description:  A simple server that responds with the http headers it received
name: echoserver
version: 0.0.13
keywords:
  - infrastructure
home: https://wikitech.wikimedia.org/wiki/Echoserver
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/operations/docker-images/production-images
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: SRE Service Operations
    email: sre-service-ops@wikimedia.org