apiVersion: v2
name: calico-crds
description: Calico Custom Resource Definitions
type: application
version: 0.3.1
appVersion: 3.30.7
# skip ci checks for this Chart.yaml
annotations:
  skip-checks: "team,maintainers,home,sources"