# WMF staging main release specific values.

app:
  # These are set in common values.yaml file.
  # Change them here if you need to override them for the staging release.
  #
  # version: v1.56.0-dev18
  # logConfiguration:
  #   rootLogger.level: INFO

  taskManager:
    # NOTE: parallelism == TM replicas * numberOfTaskSlots.
    replicas: 2
    resource:
      cpu: 2
      memory: 3000m

  flinkVersion: v2_0

  job:
    jarURI: local:///srv/app/usrlib/app-with-dependencies.jar
    entryClass: org.wikimedia.mediawiki.event.enrichment.pagetrending.PageTrending

    # Using stateless only for staging.
    upgradeMode: stateless

  config_files:
    page-trending.properties:
      kafka-bootstrap-servers: kafka-test-eqiad.external-services.svc.cluster.local:9093
      kafka-consumer-group-id: staging.pageview-trending-relative-next__dse-k8s-eqiad.001
      topic-prefix: staging
      event-stream-json-schema-urls: file:///srv/app/resources/schema_repo


  flinkConfiguration:
    # Parallelism == taskManager.replicas * numberOfTaskSlots.
    # Having fewer TMs results in slightly better resource allocation.
    "taskmanager.numberOfTaskSlots": 2
    # Set the staging release specific HA storageDir path.
    # Note: Naming convention is different than in mw-page-content-change-enrich-next due to swift template in flink chart
    "high-availability.storageDir": "s3://pageview-trending-relative-next.dse-k8s-eqiad/staging/high-availability"

flink:
  object_store:
    # Set the staging release specific objectstore bucket
    swift_bucket: pageview-trending-relative-next.dse-k8s-eqiad

external_services:
  kafka: [test-eqiad]
