app:
  # Temporarily override the image here, while we roll out the new Airflow version to all instances sequentially. This will be removed once the upgrade is complete.
  version: &base-image-version airflow-2.11.2-py3.11-2026-04-16-134304-f4802bd4391b8fc561804913728472d5a2721d42@sha256:976f939064787fa65c1c551e72f697120e611e5610441d6869c7523d723d429b
  executor_pod_image_version: *base-image-version

config:
  airflow:
    instance_name: wikidata
  connections:
    wikidata_platform_s3_dpe:
      conn_type: aws
      extra:
        endpoint_url: https://rgw.eqiad.dpe.anycast.wmnet
        region_name: dpe
      login: "{{ $.Values.config.connections.wikidata_platform_s3_dpe.aws_access_key_id }}"
      password: "{{ $.Values.config.connections.wikidata_platform_s3_dpe.aws_secret_access_key }}"
  extra_secrets:
    # Create a secret object with the same values as the corresponding airflow connection.
    # This may be useful if running a task based on a KubernetesPodOperator that does not use the airflow image.
    wikidata_platform_s3_dpe.yaml: |
      username: "{{ $.Values.config.connections.wikidata_platform_s3_dpe.aws_access_key_id }}"
      password: "{{ $.Values.config.connections.wikidata_platform_s3_dpe.aws_secret_access_key }}"

ingress:
  gatewayHosts:
    default: "airflow-wikidata"
    extraFQDNs:
    - airflow-wikidata.wikimedia.org
