# This file is used to override the production values defaults for the canary release.

# route canary access through the main release
routed_via: main

service:
  # Don't deploy a k8s Service for this canary release
  deployment: none

resources:
  # 3% of main replicas, rounded up.
  replicas: 6

# There is no point for a rolling release for canaries, recreate them T375477
strategy:
  type: Recreate
  rollingUpdate: ~ # This is here to ensure globals are overriden

# T364245: (begin) experimental changes (envoy drain testing)
mesh:
  image_version: 1.35.7-6
  drain: true
  admin:
    # Apply graceful drain (DRAIN_GRACEFUL) over a 3s window.
    drain_time_s: 3 # Overrides default (600).
    drain_strategy: "immediate"  # Overrides default (gradual).
  extra_env:
    # Use the tool, which supports admin-over-UDS.
    DRAIN_VIA_TOOL: true
    # Tell the tool where to find the socket.
    ADMIN_SOCKET: /var/run/envoy/admin.sock
    # Trigger graceful drain, applied over admin.drain_time_s.
    DRAIN_GRACEFUL: true
    # Trigger inboundonly drain, leaving outbound mesh listeners running.
    DRAIN_INBOUND_ONLY: true
    # Ensure that the post-drain wait period (i.e., waiting active connections
    # to drain) lasts at least as long as mediawiki's pre-stop sleep hook.
    DRAIN_WAIT_MINIMUM_S: 8
# T364245: (end) experimental changes
