resources:
# When ramping up replicas in the main release, please remember
# to raise the number of canary replicas as well.
# We aim for ~3% of the deployment for canaries, rounding up.
  # October 2025 sizing for *multi-DC* serving:
  replicas: 180
  # September 2025 Switchover sizing (estimated) for *single-DC* serving:
  #replicas: 230

mesh:
  image_version: 1.35.9-1
  public_port: 4446
  tracing:
    enabled: true
    sampling: 0.01
  # T364245: (begin) experimental changes (envoy drain testing)
  drain: true
  admin:
    # Apply graceful drain (DRAIN_GRACEFUL) over a 3s window.
    drain_time_s: 3 # Overrides default (600).
    drain_strategy: "immediate"  # Overrides default (gradual).
  extra_env:
    # Use the tool, which supports admin-over-UDS.
    DRAIN_VIA_TOOL: true
    # Tell the tool where to find the socket.
    ADMIN_SOCKET: /var/run/envoy/admin.sock
    # Trigger graceful drain, applied over admin.drain_time_s.
    DRAIN_GRACEFUL: true
    # Trigger inboundonly drain, leaving outbound mesh listeners running.
    DRAIN_INBOUND_ONLY: true
    # Ensure that the post-drain wait period (i.e., waiting active connections
    # to drain) lasts at least as long as mediawiki's pre-stop sleep hook.
    DRAIN_WAIT_MINIMUM_S: 8
  # T364245: (end) experimental changes

monitoring:
  statsd: ~

main_app:
  requests:
    auto_compute: true
  limits:
    auto_compute: true
    enforce: true
    cpu: ~
