-- Tests for the Lua filters
-- File under test:
local thisdir = debug.getinfo(1).source:match("@?(.*/)") or "."


function loadf(path)
    local f = assert(io.open(path))
    local s = assert(f:read('*a'))
    f:close()
    return s
end

-- Load and run code under test.
-- We need a helper script, because the code is generated by a helm template.
local codeFile = os.tmpname()
os.execute( thisdir .. "/get-lua.sh > " .. codeFile)
local codeString = loadf(codeFile)
local codeFunc = loadstring(codeString)

if not codeFunc then
    print( "Code under test is invalid:" )
    os.execute( "lua " .. codeFile )
    os.exit(3)
    os.remove(codeFile)
end

os.remove(codeFile)
codeFunc()

-- This uses the Busted test framework, see https://lunarmodules.github.io/busted/.
-- The structure is similar to Mocha tests.
-- Installation: luarocks install busted

describe("rest_hooks", function()
    function add_getters(obj, values)
        for k, v in pairs(values) do
            obj[k] = function () return v end
        end

        return obj
    end

    function fake_headers(values)
        local headers = { values = values }

        -- clone
        for k, v in pairs(values) do headers.values[k] = v end

        -- fake methods
        -- Note that add() is implemented like replace(). Good enough for now.
        headers.get = function(h, k) return h.values[k] end
        headers.add = function(h, k, v) h.values[k] = v end
        headers.replace = function(h, k, v) h.values[k] = v end
        headers.remove = function(h, k) h.values[k] = nil end

        return headers
    end

    function fake_metadata(values)
        return {
            get = function(h, k) return values[k] end
        }
    end

    function fake_stream_info(address, metadata)
        return add_getters( {},{
            downstreamRemoteAddress = address,
            dynamicMetadata = fake_metadata(metadata),
        })
    end

    function noop() end

    function fake_request_handle(arg)
        local headers = arg.headers or { ["x-client-ip"] = "192.168.1.1" }

        return add_getters( {
            logDebug = noop,
            logInfo = noop,
            logWarning = noop,
        },{
            headers = fake_headers(headers),
            streamInfo = fake_stream_info(arg.address or "127.0.0.1",
                    arg.streamMetadata or {}),
            metadata = fake_metadata(arg.routeMetadata or {}),
        })
    end

    describe("wmf_ratelimit_info", function()
        describe("policy handling", function()
            it("should set x-wmf-ratelimit-policy based on route metadata", function()
                local routeMeta = { ["wmf_ratelimit"] = { ["policy"] = "just-a-test" } }
                local req = fake_request_handle( { routeMetadata = routeMeta } )
                wmf_ratelimit_info(req)

                local result = req:headers()
                assert.are.equal( "just-a-test", result:get("x-wmf-ratelimit-policy") )
            end)
        end)
        describe("address handling", function()
            it("should bypass rate limiting if x-client-ip is not set", function()
                local headers = {} -- suppress default headers
                local req = fake_request_handle( { headers = headers } )
                wmf_ratelimit_info(req)

                local result = req:headers()

                assert.are.equal( nil, result:get("x-wmf-user-id") )
                assert.are.equal( nil, result:get("x-wmf-ratelimit-class") )
                -- test-fallback-class is specified in values-test.yaml.
            end)
            it("should use the x-client-ip as the user ID, and assign the fallback class", function()
                local headers = { ["x-client-ip"] = "203.0.113.222" }
                local req = fake_request_handle( { headers = headers } )
                wmf_ratelimit_info(req)

                local result = req:headers()
                assert.are.equal( "203.0.113.222", result:get("x-wmf-user-id") )
                assert.are.equal( "test-fallback-class", result:get("x-wmf-ratelimit-class") )
                assert.are.equal( "MISSING", result:get("x-wmf-ratelimit-policy") )
            end)
        end)
        describe("header handling", function()
            it("should use the x-wmf-user-id header if given", function()
                local routeMeta = { ["wmf_ratelimit"] = { ["policy"] = "just-a-test" } }
                local headers = { ["x-wmf-user-id"] = "Cindy", ["x-client-ip"] = "192.168.1.1" }
                local req = fake_request_handle( { routeMetadata = routeMeta, headers = headers } )
                wmf_ratelimit_info(req)

                local result = req:headers()
                assert.are.equal( "Cindy", result:get("x-wmf-user-id") )
                assert.are.equal( "test-fallback-class", result:get("x-wmf-ratelimit-class") )
                assert.are.equal( "just-a-test", result:get("x-wmf-ratelimit-policy") )
                -- test-fallback-class is specified in values-test.yaml.
            end)
            it("should use the x-wmf-ratelimit-class header if given", function()
                local routeMeta = { ["wmf_ratelimit"] = { ["policy"] = "just-a-test" } }
                local headers = {
                    ["x-wmf-user-id"] = "Cindy",
                    ["x-wmf-ratelimit-class"] = "CindysClass",
                    ["x-client-ip"] = "192.168.1.1",
                }
                local req = fake_request_handle( { routeMetadata = routeMeta, headers = headers } )
                wmf_ratelimit_info(req)

                local result = req:headers()
                assert.are.equal( "Cindy", result:get("x-wmf-user-id") )
                assert.are.equal( "CindysClass", result:get("x-wmf-ratelimit-class") )
                assert.are.equal( "just-a-test", result:get("x-wmf-ratelimit-policy") )
            end)
        end)
        describe("cookie handling", function()
            it("should use the user ID from the cookie", function()
                -- cookie values are expected to be stored in stream metadata
                -- TestUserID is specified in values-test.yaml.
                streamMetadata = { ["envoy.wmf_cookies"] = { ["TestUserID"] = "Cindy" } }
                local req = fake_request_handle( { streamMetadata = streamMetadata } )
                wmf_ratelimit_info(req)

                local result = req:headers()
                assert.are.equal( "Cindy", result:get("x-wmf-user-id") )
                assert.are.equal( "cookie-user", result:get("x-wmf-ratelimit-class") )
                assert.are.equal( "MISSING", result:get("x-wmf-ratelimit-policy") )
            end)
        end)
    end)

    describe("wmf_ratelimit_cleanup", function()
        function assertHeaderUpate( headerName, headerValue, expectedResult )
            local headers = { test = "foobar" }
            headers[headerName] = headerValue

            local req = fake_request_handle{headers = headers}

            wmf_ratelimit_cleanup( req )

            local result = req:headers()
            assert.are.equal("foobar", result:get("test"))
            assert.are.equal(expectedResult, result:get(headerName))
        end

        it("should unset x-wmf-ratelimit-class header if it is 'no-limit'", function()
            assertHeaderUpate("x-wmf-ratelimit-class", "no-limit", nil)
        end)

        it("should preserve x-wmf-ratelimit-class header if it is 'some-class'", function()
            assertHeaderUpate("x-wmf-ratelimit-class", "some-class", "some-class")
        end)

        it("should unset x-wmf-ratelimit-policy header if it is 'no-limit'", function()
            assertHeaderUpate("x-wmf-ratelimit-policy", "no-limit", nil)
        end)

        it("should preserve x-wmf-ratelimit-policy header if it is 'some-policy'", function()
            assertHeaderUpate("x-wmf-ratelimit-policy", "some-policy", "some-policy")
        end)

        it("should preserve x-something-else header even if it is 'no-limit'", function()
            assertHeaderUpate("x-something-else", "no-limit", "no-limit")
        end)
    end)
end)