main_app:
  image: repos/projects/wmf-navigator
  version: 2026-05-28-182504-web
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
  volumes:
    - name: miscweb-wmf-navigator-secret-config
      secret:
        secretName: miscweb-wmf-navigator-secret-config
    - name: data-sync-output-dir
      emptyDir: {}

sidecars:
  navigator-backend:
    enabled: true
    image: repos/projects/wmf-navigator
    version: 2026-05-28-182504-navigator-backend
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
    volumeMounts:
      - name: data-sync-output-dir
        mountPath: /data
    config:
      public:
        DATA_DIR: '/data'
        PORT: '3000'
        CORS_ORIGINS: 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080'
        HTTP_PROXY: "http://url-downloader.eqiad.wikimedia.org:8080"
        HTTPS_PROXY: "http://url-downloader.eqiad.wikimedia.org:8080"
        NO_PROXY: "localhost,127.0.0.1,office.wikimedia.org"
        NODE_USE_ENV_PROXY: 1
  data-sync:
    enabled: true
    image: repos/projects/wmf-navigator
    version: 2026-05-28-182504-data-sync
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
    volumeMounts:
      - name: data-sync-output-dir
        mountPath: /data
      - name: miscweb-wmf-navigator-secret-config
        mountPath: /etc/secrets/google_application_credentials.json
        subPath: GOOGLE_APPLICATION_CREDENTIALS_SECRET
        readOnly: true
      - name: miscweb-wmf-navigator-secret-config
        mountPath: /etc/secrets/okta_users_api_private_key.pem
        subPath: OKTA_PRIVATE_KEY
        readOnly: true
    command: ["/bin/sh", "-c", "/app/packages/data-sync/bin/sync-to-data-dir.sh; sleep 3600"]
    config:
      public:
        DATA_DIR: '/data'
        HTTP_PROXY: "http://url-downloader.eqiad.wikimedia.org:8080"
        HTTPS_PROXY: "http://url-downloader.eqiad.wikimedia.org:8080"
        NO_PROXY: "localhost,127.0.0.1,office.wikimedia.org"
        NODE_USE_ENV_PROXY: 1
        OFFICE_WIKI_BASE_URL: "http://localhost:6501"
        MEDIAWIKI_BASE_URL: "http://localhost:6501"
        GOOGLE_APPLICATION_CREDENTIALS: "/etc/secrets/google_application_credentials.json"
mesh:
  enabled: true
  public_port: 4111

ingress:
  enabled: true
  gatewayHosts:
    extraFQDNs:
    - wmf-navigator.wikimedia.org
external_services:
  urldownloader: [wikimedia]

discovery:
  listeners:
    - mw-api-int

networkpolicy:
  egress:
    enabled: true