main_app:
  image: httpd
  version: 2.4.62-1-20260315
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

mesh:
  enabled: true
  public_port: 4111

ingress:
  enabled: true
  gatewayHosts:
    extraFQDNs:
    - wmf-navigator.wikimedia.org
