sidecars:
  data-sync:
    config:
      public:
        HTTP_PROXY: "http://urldownloader.svc.codfw.wmnet:8080"
        HTTPS_PROXY: "http://urldownloader.svc.codfw.wmnet:8080"
  navigator-backend:
    config:
      public:
        HTTP_PROXY: "http://urldownloader.svc.codfw.wmnet:8080"
        HTTPS_PROXY: "http://urldownloader.svc.codfw.wmnet:8080"
