main_app:
  datacentre: eqiad
  cassandra_hosts:
    - restbase1031-a.eqiad.wmnet:9042
    - restbase1031-b.eqiad.wmnet:9042
    - restbase1031-c.eqiad.wmnet:9042
    - restbase1032-a.eqiad.wmnet:9042
    - restbase1032-b.eqiad.wmnet:9042
    - restbase1032-c.eqiad.wmnet:9042
    - restbase1033-a.eqiad.wmnet:9042
    - restbase1033-b.eqiad.wmnet:9042
    - restbase1033-c.eqiad.wmnet:9042
    - restbase1034-a.eqiad.wmnet:9042
    - restbase1034-b.eqiad.wmnet:9042
    - restbase1034-c.eqiad.wmnet:9042
    - restbase1035-a.eqiad.wmnet:9042
    - restbase1035-b.eqiad.wmnet:9042
    - restbase1035-c.eqiad.wmnet:9042
    - restbase1036-a.eqiad.wmnet:9042
    - restbase1036-b.eqiad.wmnet:9042
    - restbase1036-c.eqiad.wmnet:9042
    - restbase1037-a.eqiad.wmnet:9042
    - restbase1037-b.eqiad.wmnet:9042
    - restbase1037-c.eqiad.wmnet:9042
    - restbase1038-a.eqiad.wmnet:9042
    - restbase1038-b.eqiad.wmnet:9042
    - restbase1038-c.eqiad.wmnet:9042
    - restbase1039-a.eqiad.wmnet:9042
    - restbase1039-b.eqiad.wmnet:9042
    - restbase1039-c.eqiad.wmnet:9042
    - restbase1040-a.eqiad.wmnet:9042
    - restbase1040-b.eqiad.wmnet:9042
    - restbase1040-c.eqiad.wmnet:9042
    - restbase1041-a.eqiad.wmnet:9042
    - restbase1041-b.eqiad.wmnet:9042
    - restbase1041-c.eqiad.wmnet:9042
    - restbase1042-a.eqiad.wmnet:9042
    - restbase1042-b.eqiad.wmnet:9042
    - restbase1042-c.eqiad.wmnet:9042
    - restbase1043-a.eqiad.wmnet:9042
    - restbase1043-b.eqiad.wmnet:9042
    - restbase1043-c.eqiad.wmnet:9042
    - restbase1044-a.eqiad.wmnet:9042
    - restbase1044-b.eqiad.wmnet:9042
    - restbase1044-c.eqiad.wmnet:9042
    - restbase1045-a.eqiad.wmnet:9042
    - restbase1045-b.eqiad.wmnet:9042
    - restbase1045-c.eqiad.wmnet:9042

external_services:
  cassandra:
    # Allow egress to the entire cluster (both sites).
    - restbase-storage-a-codfw
    - restbase-storage-b-codfw
    - restbase-storage-a-eqiad
    - restbase-storage-b-eqiad
