main_app:
  image: repos/wmde/wikidata-query-builder
  version: 2026-08-27-173902
  readiness_probe:
    httpGet:
      path: /querybuilder

ingress:
  enabled: true
  existingGatewayName: "miscweb-wikidata-query-gui"
  routeHosts:
  - query.wikidata.org
  httproutes:
  - match:
    - uri:
        prefix: /querybuilder
    route:
    - destination:
        host: miscweb-wikidata-query-builder-tls-service.wikidata-query-gui.svc.cluster.local
        port:
          number: 8081