# WMF production main release specific values.

app:
  # These are set in common values.yaml file.
  # Change them here if you need to override them for the production release.
  #
  # version: v1.52.0
  # logConfiguration:
  #   rootLogger.level: INFO

  taskManager:
    # NOTE: parallelism == TM replicas * numberOfTaskSlots.
    replicas: 10
    resource:
      cpu: 2
      memory: 6000m

  config_files:
    app.config.yaml:

      # Configs for eventutilities python stream_manager.
      stream_manager:
        job_name: mw-page-html-content-change-enrich

        # Configure sources and sinks.
        source:
          stream: mediawiki.page_change.v1:1.3.0
          # source parallelism shoudl probably be set to the number of input Kafka topic-partitions.
          # mediawiki.page_change.v1 is made up of two topics, each of one partition
          # (as of 2026-04)
          parallelism: 2
          options:
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            # Kafka consumer group naming follows convention: <job_name>__<k8s_cluster_name>
            consumer_group: mw-page-html-content-change-enrich__dse-k8s-eqiad.001

        sink:
          stream: mediawiki.page_html_content_change.dev5:1.0.0
          options:
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            kafka_topic_prefix: eqiad.

        error_sink:
          stream: mw_page_html_content_change_enrich.error:2.1.0
          options:
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            kafka_topic_prefix: eqiad.

  job:
    # TODO: we might consider setting
    # kubernetes.operator.job.upgrade.last-state.max.allowed.checkpoint.age.
    # to fallback on savepoints if checkpoints are too old.
    # This might require changing checkpoint retention policy.
    upgradeMode: last-state


  flinkConfiguration:
    # Parallelism == taskManager.replicas * numberOfTaskSlots.
    # Having fewer TMs results in slightly better resource allocation.
    "taskmanager.numberOfTaskSlots": 4
    # Set the production release specific HA storageDir path.
    # Note: Naming convention is different than in mw-page-content-change-enrich due to swift template in flink chart
    "high-availability.storageDir": "s3://mw-page-html-content-change-enrich.dse-k8s-eqiad/production/high-availability"


flink:
  object_store:
    # Set the production release specific objectstore bucket
    swift_bucket: mw-page-html-content-change-enrich.dse-k8s-eqiad

external_services:
  kafka:  [jumbo-eqiad]
