# NOTE: values-dse-k8s-eqiad.yaml is configured to be deployed in dse-k8s-eqiad k8s.

service:
  deployment: production

app:
  taskManager:
    # Otto: increase to 40 TaskManagers to test backfill throughput for our first deployment.
    # TODO: reset this to something lower for regular operation.
    replicas: 40
    resource:
      cpu: 2
      memory: 3000m

  config_files:
    app.config.yaml:

      # Configs for eventutilities python stream_manager.
      stream_manager:
        # Configure sources and sinks.
        source:
          # This should probably be set to the number of input Kafka topic-partitions.
          # mediawiki.page_change.v1 is made up of two topics, each of one partition
          # (as of 2026-04)
          parallelism: 2
          options:
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            # Running in Jumbo we should consume both eqiad and codfw
            topics: [eqiad.mediawiki.page_change.v1, codfw.mediawiki.page_change.v1]
            # Kafka consumer group naming follows convention: <job_name>__<k8s_cluster_name>
            consumer_group: mw-page-html-content-change-enrich__dse-k8s-eqiad.000

        sink:
          options:
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            kafka_topic_prefix: eqiad.

        error_sink:
          options:
            bootstrap_servers: kafka-jumbo-eqiad.external-services.svc.cluster.local:9093
            kafka_topic_prefix: eqiad.

flink:
  object_store:
    swift_cluster: https://rgw.eqiad.dpe.anycast.wmnet
