apiVersion: v2
description: A Helm chart for Kubernetes
name: matomo
version: 0.0.1
home: https://wikitech.wikimedia.org/somepage
team: team name or team wiki URL
maintainers:
  - name: Brian King
    email: bking@wikimedia.org
sources:
  - https://website.org/for/upstream/chart/or/image/definition
keywords:
  - analytics
  - matomo
  - piwik
