apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: disallow-host-ports-none
  annotations:
    kyverno_policy_name: disallow-host-ports
    kyverno_rule_name: host-ports-none
    psa_profile: baseline
spec:
  matchConstraints:
    resourceRules:
    - apiGroups: ['']
      apiVersions: ['*']
      operations: [CREATE, UPDATE]
      resources: [pods]
  variables:
  - name: allContainers
    expression: |-
      object.spec.containers +  object.spec.?initContainers.orValue([]) +
      object.spec.?ephemeralContainers.orValue([])
  validations:
  - expression: |-
      variables.allContainers.all(container,  container.?ports.orValue([]).all(port,
      port.?hostPort.orValue(0) == 0))
    message: >-
      Use of host ports is disallowed. The fields spec.containers[*].ports[*].hostPort,
      spec.initContainers[*].ports[*].hostPort, and spec.ephemeralContainers[*].ports[*].hostPort
      must either be unset or set to `0`.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: disallow-host-ports-none
spec:
  policyName: disallow-host-ports-none
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pod-security.wmf.org/profile
        operator: In
        values:
        - baseline
        - restricted
      - key: pod-security.wmf.org/disallow-host-ports-none
        operator: NotIn
        values:
        - exclude
  validationActions: {{ get (default dict .Values.validatingActions) "disallow-host-ports-none" | default (list "Deny") | toYaml | nindent 4 }}
