config:
  airflow:
    instance_name: fr-tech
  connections:
    s3_fr_tech:
      conn_type: aws
      extra:
        endpoint_url: https://franio1001.frack.eqiad.wmnet:9000
        region_name: us-east-1
        verify: /etc/ssl/certs/wmf-ca-certificates.crt

ingress:
  gatewayHosts:
    default: "airflow-fr-tech"
    extraFQDNs:
    - airflow-fr-tech.wikimedia.org

external_services:
  task-pod:
    minio:
    - fr-tech-eqiad
