apiVersion: v2
description: Helm chart for the iPoid service
name: ipoid
kubeVersion: ">=1.23"
version: 0.2.17
keywords:
  - iPoid
  - ipoid
  - IP
  - IP address
home: https://wikitech.wikimedia.org/wiki/IPoid
sources:
  - https://gitlab.wikimedia.org/repos/mediawiki/services/ipoid
team: https://wikitech.wikimedia.org/wiki/Product_Safety_and_Integrity
maintainers:
  - name: Tran
    email: tran@wikimedia.org
  - name: Kosta Harlan
    email: kharlan@wikimedia.org
  - name: Effie Mouzeli
    email: effie@wikimedia.org