-- -----------------------------------------------------------------------
-- Use test cases in tests/lua/test_restgw_headers.lua to protect the logic in this file!
-- -----------------------------------------------------------------------

-- Stash essential request properties before jwt_authn may strip headers.
-- These are needed in the response phase to set CORS headers.
function wmf_stash_request_info(request_handle)
    local req_headers = request_handle:headers()
    local streamMeta = request_handle:streamInfo():dynamicMetadata()
    for _, hname in ipairs({ ":path", ":method", "origin" }) do
        local hvalue = req_headers:get(hname)
        if hvalue then
            streamMeta:set("envoy.wmf_request_info", hname, hvalue)
        end
    end
end

-- CORS Access-Control headers for Envoy-generated local replies, see T418969.
--
-- This runs in the early filter (before jwt_authn) so that it also handles
-- local replies generated by jwt_authn itself (e.g. 401 Unauthorized).
-- CORS Access-Control headers, see T418969
function wmf_set_cors_access_control(response_handle)
    local headers = response_handle:headers()

    -- Only add CORS headers to responses generated by Envoy itself, not upstream responses.
    -- HACK: Use x-envoy-upstream-service-time to decide whether the response is proxied
    -- from an upstream service.
    -- TODO: replace this with responseCodeDetails() == "via_upstream" once that method is
    -- available in Envoy's Lua filter StreamInfo API.
    if headers:get("x-envoy-upstream-service-time") then return end

    -- Get stashed request headers
    local streamMeta = response_handle:streamInfo():dynamicMetadata()
    local request_info = streamMeta:get("envoy.wmf_request_info")
    if not request_info then return end

    -- OPTIONS have to be handled by the upstream service, not by this function.
    -- We could also check the :status header here and only add the headers for certain responses.
    local method = request_info[":method"]
    if method == "OPTIONS" then return end

    -- If we don't have an Origin header in the request, do nothing.
    local origin = request_info["origin"]
    if not origin then return end

    -- Opaque origin, see https://developer.mozilla.org/en-US/docs/Glossary/Origin#opaque_origin
    if origin == "null" then return end

    -- NOTE: While validating the origin is necessary to avoid leaking information to external
    -- websites, it is sufficient if the upstream does that when handling the preflight request.
    -- This code doesn't run for OPTIONS requests and only for responses generated by Envoy.
    headers:replace("Access-Control-Allow-Credentials", "true")
    headers:replace("Access-Control-Allow-Origin", origin)
    headers:add("Access-Control-Expose-Headers", "Retry-After,WWW-Authenticate")
end

function envoy_on_request(request_handle)
    wmf_stash_request_info(request_handle)
end

function envoy_on_response(response_handle)
    wmf_set_cors_access_control(response_handle)
end
