apiVersion: v2
name: function-evaluator
version: 0.3.19
description: A Helm chart for running the Wikifunctions evaluator back-end services on Kubernetes for a specified language
kubeVersion: ">=1.31"
keywords:
 - wikifunctions
 - abstract-wikipedia
home: https://wikitech.wikimedia.org/wiki/Wikifunctions
sources:
 - https://gitlab.wikimedia.org/repos/abstract-wiki/wikifunctions/function-evaluator
maintainers:
  - name: James Forrester
    email: jforrester@wikimedia.org
  - name: Cory Massaro
    email: cmassaro@wikimedia.org
team: https://wikitech.wikimedia.org/wiki/Wikifunctions
