config:
  airflow:
    instance_name: analytics-product
  connections:
    wme_metrics:
      conn_type: http
      host: https://wme-metrics-a699af2493d4.auth.us-east-1.amazoncognito.com
    extra:
        metrics_endpoint: https://metrics.wikimediaenterprise.org/enterprise-metrics
ingress:
  gatewayHosts:
    default: "airflow-analytics-product"
    extraFQDNs:
    - airflow-analytics-product.wikimedia.org

external_services:
  task-pod:
    gitlab: [wikimedia]

worker:
  proxy:
    urldownloader:
      enabled: true