apiVersion: v2
description: A Helm chart for Kubernetes sidecar controller
name: k8s-controller-sidecars
version: 0.0.5
keywords:
  - infrastructure
home: https://wikitech.wikimedia.org/wiki/K8s-controller-sidecars
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/operations/docker-images/production-images
  - https://github.com/otherguy/k8s-controller-sidecars
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: SRE Service Operations
    email: sre-service-ops@wikimedia.org