app:
  version: v1.4.5-prod

  service:
    user_agent: Test Kitchen UI/1.4 (#experiment-platform)

  logging:
    level: debug

  database:
    database: test_kitchen_production
    username: test_kitchen_production

  listeners:
    action_api_basepath: http://127.0.0.1:6500

  idp:
    oidc_url: https://idp.wikimedia.org/oidc
    client_id: test_kitchen
    redirect_uri: https://test-kitchen.wikimedia.org/login/callback

  growthbook:
    include_gb: true
    include_tk: true
    # http://localhost:6049 is proxied to growthbook-api
    api_url: http://localhost:6049/api/v1/experiments
    ui_url: https://growthbook.wikimedia.org/experiments

ingress:
  gatewayHosts:
    extraFQDNs:
    - test-kitchen.wikimedia.org

discovery:
  listeners:
  - mw-api-int-async-ro
  - growthbook-api
