apiVersion: v2
description: A Helm chart for Kubernetes
name: etherpad
version: 0.0.1
home: https://wikitech.wikimedia.org/wiki/Etherpad.wikimedia.org#Chart
team: https://wikitech.wikimedia.org/wiki/SRE/Collaboration_Services
maintainers:
  - name: Jelto Wodstrcil
    email: jwodstrcil@wikimedia.org
sources:
  - https://website.org/for/upstream/chart/or/image/definition
keywords:
  - etherpad
  - collab
  - pad
  - aux