apiVersion: v2
appVersion: "1.12.1"
description: A coredns deployment for WMF clusters
keywords:
  - infrastructure
name: coredns
version: 0.6.0
home: https://wikitech.wikimedia.org/wiki/CoreDNS
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/
team: https://www.mediawiki.org/wiki/Kubernetes_SIG
maintainers:
  - name: Kubernetes SIG
    email: kubernetes-sig@lists.wikimedia.org