apiVersion: v2
appVersion: "1.11.3"
description: A coredns deployment for WMF clusters
keywords:
  - infrastructure
name: coredns
version: 0.5.0
home: https://wikitech.wikimedia.org/wiki/CoreDNS
sources:
  - https://gerrit.wikimedia.org/r/plugins/gitiles/operations/docker-images/production-images/
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: SRE Service Operations
    email: sre-service-ops@wikimedia.org
