# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

k8s_app: kube-dns

# When true, this CoreDNS instance is restricted to internal domains only: Kubernetes cluster.local
# addresses will resolve, and anything in *.wmnet will be forwarded through /etc/resolv.conf, but
# everything else will come back NXDOMAIN instead of recursing to external DNS resolvers on the
# internet.
internal_only: false

replicaCount: 2

image:
  repository: docker-registry.wikimedia.org/coredns
  # Overrides the images tags (whose default is the chart appVersion).
  tag: ""
  pullPolicy: IfNotPresent

service:
  clusterIP:
  # Nil, or a port number on which to expose coredns.
  nodePort: ~

resources:
  limits:
    memory: 170Mi
  requests:
    cpu: 100m
    memory: 70Mi

nodeSelector: {}

tolerations: []

affinity: {}
