# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

k8s_app: kube-dns

# When true, this CoreDNS instance is restricted to internal domains only: Kubernetes cluster.local
# addresses will resolve, and anything in *.wmnet will be forwarded through /etc/resolv.conf, but
# everything else will come back NXDOMAIN instead of recursing to external DNS resolvers on the
# internet.
internal_only: false

# When enabled, configure the kubepods plugin which synthesizes A, AAAA, and PTR records for Pod addresses.
# See: https://github.com/coredns/kubepods
kubepods: false

# Internal message rewriting rules, see: https://coredns.io/plugins/rewrite/
# These will apply to all server blocks.
# rewrite_actions:
#   continue: []
#   stop: []

replicaCount: 2

image:
  repository: docker-registry.wikimedia.org/coredns1.12
  # Overrides the images tags (whose default is the chart appVersion).
  tag: ""
  pullPolicy: IfNotPresent

service:
  clusterIP:
  # Nil, or a port number on which to expose coredns.
  nodePort: ~

resources:
  limits:
    memory: 170Mi
  requests:
    cpu: 100m
    memory: 70Mi

nodeSelector: {}

tolerations: []

affinity: {}
