apiVersion: v2
description: Helm chart for Kask on WMF Kubernetes infrastructure
kubeVersion: ">=1.8"
name: kask
version: 0.2.11
dependencies:
  # cassandra can be deployed for developement purposes
  # Note we are using an incubator cassandra chart for this
  # Make sure you have ran
  # helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
  - name: cassandra
    version: ">= 0.11.1"
    repository: https://charts.helm.sh/incubator
  # Only require cassandra if subcharts.cassandra is set to true in values
  # or --set subcharts.cassandra=true
    condition: subcharts.cassandra
keywords:
  - session
  - store
home: https://wikitech.wikimedia.org/wiki/Kask
sources:
  - https://gitlab.wikimedia.org/repos/mediawiki/services/kask
team: https://wikitech.wikimedia.org/wiki/SRE/Data_Persistence
maintainers:
  - name: Eric Evants
    email: eevans@wikimedia.org