main_app:
  version: 2026-03-31-173458-production
  log_level: debug
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 500m
    memory: 500Mi

resources:
  replicas: 1

ingress:
  staging: true
