releases:
  - name: namespaces
    chart: wmf-stable/raw
    namespace: kube-system
    values:
      - templates:
      {{/* Merge (and overwrite) services (defined in hiera) with namespaces (defined in admin_ng values) */}}
      {{- range $service_name, $values := mergeOverwrite .Values.services .Values.namespaces }}
        {{/* If the namespace name is undefined, use the service name */}}
        {{ $namespace_name := $values | get "namespace" $service_name }}
        {{/* Don't mess with Kubernetes builtin namespaces while still allow to deploy to it */}}
        {{ $isBuiltinNamespace := or (eq (hasPrefix "kube-" $namespace_name) true) (eq $namespace_name "default") }}
        {{/* All builtin namespaces are system namespaces */}}
        {{ $isSystemNamespace := $values | get "systemNamespace" $isBuiltinNamespace }}
        {{- if eq $isBuiltinNamespace false }}
          - |
            apiVersion: v1
            kind: Namespace
            metadata:
              name: {{ $namespace_name }}
              {{- $labels := $values | get "labels" dict }}
              {{/* If no pod-security.wmf.org/profile label is defined for this namespace, set default pod-security labels */}}
              {{- if not (hasKey $labels "pod-security.wmf.org/profile") }}
                {{- $labels := merge $labels (dict "pod-security.kubernetes.io/audit" "restricted") }}
                {{- $labels := merge $labels (dict "pod-security.kubernetes.io/enforce" "restricted") }}
                {{- $labels := merge $labels (dict "pod-security.kubernetes.io/warn" "restricted") }}
              {{- end }}
              {{- with $labels }}
              labels:
              {{- range $k, $v := . }}
                {{ $k }}: {{ $v | quote }}
              {{- end }}
              {{- end }}
        {{- end }}
        {{- if eq $isSystemNamespace false }}
          {{/* The only namespace where readOnlyUser or deployUser is used is "ci". */}}
          {{- $defaultROUser := $values | get "readOnlyUser" $namespace_name }}
          {{- $defaultDeployUser := $values | get "deployUser" (print $namespace_name "-deploy") }}
          {{- $defaultUsernames := list (dict "name" $defaultROUser) (dict "name" $defaultDeployUser) }}
          {{- $usernames := $values | get "usernames" $defaultUsernames }}
          - |
            # Bind the deployer read-only users to the view Role for this namespace
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: view
              namespace: {{ $namespace_name }}
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: view
            subjects:
              {{- range $usernames }}
              {{- $isDeployUser := or ( hasSuffix "-deploy" .name ) ( $values | getOrNil "deployUser" | eq .name ) }}
              {{- if not $isDeployUser }}
              - apiGroup: rbac.authorization.k8s.io
                kind: User
                name: {{ .name }}
              {{- end }}
              {{- end }}
          - |
            # Bind the deployer users to the deploy Role for this namespace
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: deploy
              namespace: {{ $namespace_name }}
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: {{ $values | getOrNil "deployClusterRole" | default "deploy" }}
            subjects:
              {{- range $usernames }}
              {{- $isDeployUser := or ( hasSuffix "-deploy" .name ) ( $values | getOrNil "deployUser" | eq .name ) }}
              {{- if $isDeployUser }}
              - apiGroup: rbac.authorization.k8s.io
                kind: User
                name: {{ .name }}
              {{- end }}
              {{- end }}
          {{ $limitranges := $values | getOrNil "limitranges" | default $.Values.limitranges }}
          {{- with $limitranges}}
          {{- if or .container .pod }}
          - |
            apiVersion: v1
            kind: LimitRange
            metadata:
              name: general-limits
              namespace: {{ $namespace_name }}
            spec:
              limits:
                {{- if .container }}
                - type: Container
                  {{- if .container.min }}
                  min:
                    {{- .container.min | toYaml | nindent 20 }}
                  {{- end }}
                  {{- if .container.max }}
                  max:
                    {{- .container.max | toYaml | nindent 20 }}
                  {{- end }}
                  {{- if .container.defaultRequest }}
                  defaultRequest:
                    {{- .container.defaultRequest | toYaml | nindent 20 }}
                  {{- end }}
                  {{- if .container.default }}
                  default:
                    {{- .container.default | toYaml | nindent 20 }}
                  {{- end }}
                {{- end }}{{/* end if .container */}}
                {{- if .pod }}
                - type: Pod
                  {{- if hasKey .pod "min" }}
                  min:
                    {{- .pod.min | toYaml | nindent 20 }}
                  {{- end }}
                  {{- if hasKey .pod "max" }}
                  max:
                    {{- .pod.max | toYaml | nindent 20 }}
                  {{- end }}
                {{- end }}{{/* end if .pod */}}
          {{- end }}
          {{- end }}
          {{ $resourcequota := $values | getOrNil "resourcequota" | default $.Values.resourcequota }}
          {{- with $resourcequota }}
          {{- $count := . | get "count" list }}
          {{- if or $count .compute.requests .compute.limits }}
          - |
            apiVersion: v1
            kind: ResourceQuota
            metadata:
              name: quota-compute-resources
              namespace: {{ $namespace_name }}
            spec:
              hard:
                {{- range $resource, $c := $count }}
                count/{{ $resource }}: {{ $c }}
                {{- end }}
                {{- if .compute.requests.cpu }}
                requests.cpu: {{ .compute.requests.cpu | quote}}
                {{- end }}
                {{- if .compute.requests.memory }}
                requests.memory: {{ .compute.requests.memory | quote }}
                {{- end }}
                {{- if .compute.limits.cpu }}
                limits.cpu: {{ .compute.limits.cpu | quote }}
                {{- end }}
                {{- if .compute.limits.memory }}
                limits.memory: {{ .compute.limits.memory | quote }}
                {{- end }}
          {{- end }}
          {{- end }}
        {{- end }}{{- /* end if eq $isSystemNamespace false */}}
        {{- if $values | get "allowCriticalPods" false }}
          - |
            apiVersion: v1
            kind: ResourceQuota
            metadata:
              name: priorityclass
              namespace: {{ $namespace_name }}
            spec:
              scopeSelector:
                matchExpressions:
                  - operator: In
                    scopeName: PriorityClass
                    values:
                      - system-cluster-critical
                      - system-node-critical
        {{- end }}
      {{- end }}{{- /* end range namespaces */}}
