resources:
  replicas: 2

ingress:
  enabled: true
  gatewayHosts:
    extraFQDNs:
      - test.wikimedia.org
  httproutes:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: mediawiki-main-tls-service.mw-pretrain.svc.cluster.local
          port:
            number: 4457

mesh:
  public_port: 4457
  tracing:
    enabled: true
    sampling: 100

monitoring:
  statsd: ~

php:
  apc:
    size: 2048

service:
  nodePort: false
