# Route canary through the main jobrunner release.
routed_via: jobrunner
service:
  # Don't deploy a k8s Service for this canary release.
  deployment: none
resources:
  replicas: 1
# Do not inherit jobrunner's ingress configuration.
ingress:
  enabled: false
