templates:
  default: &default
    chart: wmf-stable/kserve-resources
    namespace: kserve
    missingFileHandler: Warn
    installedTemplate: "{{`{{ if hasKey .Environment.Values \"install_kserve_resources\" }}{{ .Environment.Values.install_kserve_resources }}{{ else }}{{ false }}{{end}}`}}"

releases:
  - name: kserve-resources
    <<: *default
    needs:
      - kube-system/namespaces
      - cert-manager/cert-manager
      - kserve/kserve-crd-minimal
    values:
      # Generic default values for all environments
      - "values/common.yaml"
      # Default values for this cluster group
      - "values/{{ .Values.cluster_group }}.yaml"
      # Environment specific defaults
      - "values/{{ .Environment.Name }}/values.yaml"
      # Release specific overrides
      - "{{`{{ .Release.Name }}`}}/values.yaml"
      # Overrides specific to release in environment
      - "values/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}-values.yaml"
      # Secrets (from private puppet repo)
      - "/etc/helmfile-defaults/private/admin/{{`{{ .Release.Name }}`}}/{{ .Environment.Name }}.yaml"
