kserve:
  version: 0.17.0-0
  controller:
    tag: 0.17.0-0
  agent:
    tag: 0.17.0-0
  router:
    tag: 0.17.0-0
  storage:
    tag: 0.17.0-0
  localmodel:
    controller:
      tag: 0.17.0-0
    agent:
      tag: 0.17.0-0
    defaultJobTag: 0.17.0-0
