apiVersion: v2
description: Helm chart for Recommendation API on WMF Kubernetes infrastructure
kubeVersion: ">=1.12"
name: recommendation-api
version: 0.1.24
keywords:
  - recommendation-api
home: https://wikitech.wikimedia.org/wiki/Services/Monitoring/recommendation_api
sources:
  - https://gerrit.wikimedia.org/g/mediawiki/services/recommendation-api
# skip ci checks for this Chart.yaml
annotations:
  skip-checks: "home,sources"