apiVersion: v2
description: A Helm chart for Kubernetes
name: sophroid
version: 0.0.5
keywords:
  - infrastructure
home: https://wikitech.wikimedia.org/wiki/Sophroid
sources:
  - https://gitlab.wikimedia.org/repos/sre/sophroid
team: https://wikitech.wikimedia.org/wiki/SRE/Service_Operations
maintainers:
  - name: SRE Service Operations
    email: sre-service-ops@wikimedia.org
  - name: Jasmine Kilani
    email: jkilani@wikimedia.org