# This file contains settings shared by all apps deployed in dse-k8s-eqiad.
#
# NOTE: This file is shared between production and staging (-next) releases.
#       In the helmfile directory, this is a symlink into a _*_common_/ values file.
#       Edits here affect both staging and production.
#       Release specific settings and overrides belong in release specific values files.
#
# Release specific settings belong in release specific values files.

service:
  deployment: production

app:
  config_files:
    app.config.yaml:

      # Configs for the page_html_content_change enrichment job in dse-k8s-eqiad
      enrich:
        # MW API requests should go to local envoy service proxy 'mwapi-async'.
        # https://gerrit.wikimedia.org/g/operations/puppet/+/refs/heads/production/hieradata/common/profile/services_proxy/envoy.yaml
        mediawiki_api_endpoint_template: http://localhost:6500/w/rest.php/v1
        ssl_ca_bundle_path: /etc/ssl/certs/ca-certificates.crt
        request_timeout: 65

      stream_manager:
        # Use synchronous processing. MW HTML API is high latency,
        # and microbatching async does not seem to help much.
        # This avoids the use of a ThreadPoolExecutor
        # for async minibatch execution.
        # Using parallelism is better. [citation needed] :)
        # https://phabricator.wikimedia.org/T421216
        # https://phabricator.wikimedia.org/T422928
        process_async_enabled_default: false

        # Requests to stream_config_uri should
        # be routed via local envoy service proxy 'mwapi-async'.
        http_client_routes:
          "https://meta.wikimedia.org/w/api.php": "http://localhost:6500"

        # Configure common settings for sources and sinks in dse-k8s
        source:
          connector: kafka
          options:
            properties:
              security.protocol: SSL
              ssl.ca.location: /etc/ssl/certs/wmf-ca-certificates.crt

        sink:
          connector: kafka
          options:
            delivery_guarantee: AT_LEAST_ONCE
            properties:
              security.protocol: SSL
              ssl.ca.location: /etc/ssl/certs/wmf-ca-certificates.crt
              # 20MB - https://phabricator.wikimedia.org/T420356
              # NOTE: eventutilities_python py4j wrapper expects a string.
              max.request.size: "20971520"

        error_sink:
          connector: kafka
          options:
            delivery_guarantee: AT_LEAST_ONCE
            properties:
              security.protocol: SSL
              ssl.ca.location: /etc/ssl/certs/wmf-ca-certificates.crt
              # 20MB - https://phabricator.wikimedia.org/T420356
              # NOTE: eventutilities_python py4j wrapper expects a string.
              max.request.size: "20971520"

  flinkConfiguration:
    # == Tuning html-content-change-enrich

    # Increase task.off-heap.size for pyflink apps with large messages.
    # Some extra memory is needed to account for large message passing to python.
    "taskmanager.memory.task.off-heap.size": 512m

    # HTML enrichment is a high latency MediaWiki API call.
    # We want to apply backpressure to tasks upstream of this
    # call as soon as possible.  Setting this allows the pyflink
    # process function to be called quickly.
    # This is especially helpful when running in synch mode
    # via stream_manager.process_async_enabled_default=False,
    # where a process function invocation may block for several seconds.
    "python.fn-execution.bundle.size": "1"

    # We encountered issues with checkpoint times as checkpoint
    # barriers propagated through the job.
    # Enable unaligned checkpointing and network buffer debloating.

    # Unaligned checkpoints should be okay for this job.
    # The size of input data is not large, so even if
    # checkpoint sizes get a little larger due to saving
    # the in-flight data, we'd prefer that over long and failed
    # checkpoint times, especially in the case of backfilling.
    # https://nightlies.apache.org/flink/flink-docs-release-2.2/docs/ops/state/checkpointing_under_backpressure/#buffer-debloating
    "execution.checkpointing.unaligned.enabled": "true"

    # The app's HTTP client request timeout is 65s (configured above).
    # Consider setting aligned-checkpoint-timeout to wait
    # at least this long for an aligned checkpoint to
    # complete before switching to an unaligned checkpoint.
    # The average HTML fetch takes between 500-1000ms.
    # Some value between 1s and 65s should be appropriate.
    #
    # If aligned checkpoints take longer than aligned-checkpoint-timeout
    # an unaligned checkpoint will be taken instead.
    "execution.checkpointing.aligned-checkpoint-timeout": 10s

    # Buffer debloating helps reduce the amount of in-flight data
    # and backpressure.
    # https://nightlies.apache.org/flink/flink-docs-release-2.2/docs/ops/state/checkpointing_under_backpressure/#buffer-debloating
    "taskmanager.network.memory.buffer-debloat.enabled": true

    # Trigger checkpoints every 10 seconds, or every 2 minutes if under backpressure.
    # NOTE: max-concurrent-checkpoints defaults to 1, even if a checkpoint
    # takes longer than this, there will never be more than one in-flight checkpoint at a time.
    "execution.checkpointing.interval": "10000" # 10 seconds.
    "execution.checkpointing.interval-during-backlog": "120000" # 2 minutes
    # NOTE: Default execution.checkpointing.timeout is 10 minutes.

    # Have flink-operator periodic savepoints for handling job restarts and upgrades.
    "kubernetes.operator.periodic.savepoint.interval": 5m
    # Keep the last 24 hours of savepoints.  Savepoint cleanup happens
    # only when the job is running, so if the job is offline e.g. over a weekend,
    # we won't going to lose the latest savepoint.
    "kubernetes.operator.savepoint.history.max.age": 24h

    # == Checkpoint, HA and restart settings
    "restart-strategy.type": exponential-delay
    "state.backend.type": hashmap
    "state.checkpoint-storage": filesystem
    "state.checkpoints.num-retained": "10"
    "s3.path.style.access": "true"
    # Enables the Kubernetes HA service.
    # Recovery metadata will be stored in a k8s ConfigMap.
    "high-availability": KUBERNETES
    # NOTE: HA paths are configured in release specific files.

    # TODO: this can be removed once https://gerrit.wikimedia.org/r/c/operations/deployment-charts/+/1268071
    #       is merged and this is the default in the chart.
    "metrics.internal.query-service.port": "6124"


flink:
  object_store:
    swift_cluster: https://rgw.eqiad.dpe.anycast.wmnet


# Enable egress.  Specific egress policies should either be added in
# environment/k8s cluster specific networkpolicy.egress.dst_nets,
# or automatically configured via discovery.listeners and/or kafka.allowed_clusters,
networkpolicy:
  egress:
    enabled: true


# Enable the service mesh.
mesh:
  enabled: true


# Enable mwapi-async envoy service proxy.
# This will forward requests to https://localhost:6500 to mw-api-int.discovery.wmnet.
discovery:
  listeners:
    - mw-api-int-async


external_services:
  s3: [eqiad-dpe]
