# DEPRECATION NOTICE
# The api-gateway is deprecated and should not get new routes added
# Please add new routes to helmfile.d/services/rest-gateway/values.yaml

main_app:
  version: 1.35.9-1
  telemetry_port: 1667

  jwt:
    enabled: true
    issuer: https://meta.wikimedia.org

  ratelimiter:
    enabled: false

  strip_api_cookies: true

  access_log:
    # Disable access log but enable 5xx logging and sample 1%
    enabled: false
    sample_percentage: 1
  normalise_paths: true

  endpoints: ~
  discovery_endpoints: ~

  readiness_probe:
    httpGet:
      path: /healthz
      port: 8087
      scheme: HTTPS


service:
  deployment: production
  port:
    nodePort: 8087

mesh:
  enabled: true
  certmanager:
    extraFQDNs:
      - '*.m.mediawiki.org'
      - '*.m.wikibooks.org'
      - '*.m.wikidata.org'
      - '*.m.wikimedia.org'
      - '*.m.wikimediafoundation.org'
      - '*.m.wikinews.org'
      - '*.m.wikipedia.org'
      - '*.m.wikiquote.org'
      - '*.m.wikisource.org'
      - '*.m.wikiversity.org'
      - '*.m.wikivoyage.org'
      - '*.m.wiktionary.org'
      - '*.mediawiki.org'
      - '*.planet.wikimedia.org'
      - '*.wikibooks.org'
      - '*.wikidata.org'
      - '*.wikimedia.org'
      - '*.wikimediafoundation.org'
      - '*.wikinews.org'
      - '*.wikipedia.org'
      - '*.wikiquote.org'
      - '*.wikisource.org'
      - '*.wikiversity.org'
      - '*.wikivoyage.org'
      - '*.wiktionary.org'
      - '*.wmfusercontent.org'
      - '*.zero.wikipedia.org'
      - 'api.wikimedia.org'
      - 'mediawiki.org'
      - 'w.wiki'
      - 'wikibooks.org'
      - 'wikidata.org'
      - 'wikimedia.org'
      - 'wikimediafoundation.org'
      - 'wikinews.org'
      - 'wikipedia.org'
      - 'wikiquote.org'
      - 'wikisource.org'
      - 'wikiversity.org'
      - 'wikivoyage.org'
      - 'wiktionary.org'
      - 'wmfusercontent.org'
      - 'api-gateway-ro.discovery.wmnet'

nutcracker:
  enabled: false

# Only used by ratelimiter for metrics - envoy uses prometheus native metrics
monitoring:
  enabled: false

networkpolicy:
  egress:
    enabled: true
    dst_nets:
    - cidr: 10.2.2.22/32 # api-rw.discovery.wmnet LVS endpoint (eqiad)
      ports:
      - protocol: tcp
        port: 443
      - protocol: tcp
        port: 80
    - cidr: 10.2.1.22/32 # api-rw.discovery.wmnet LVS endpoint (codfw)
      ports:
      - protocol: tcp
        port: 443
      - protocol: tcp
        port: 80
    - cidr: 10.2.2.1/32 # appservers-rw.discovery.wmnet LVS endpoint (eqiad)
      ports:
      - protocol: tcp
        port: 443
      - protocol: tcp
        port: 80
    - cidr: 10.2.1.1/32 # appservers-rw.discovery.wmnet LVS endpoint (codfw)
      ports:
      - protocol: tcp
        port: 443
      - protocol: tcp
        port: 80
    - cidr: 10.2.1.45/32 # eventgate-main.svc.codfw.wmnet
      ports:
        - protocol: tcp
          port: 4492
    - cidr: 10.2.2.45/32 # eventgate-main.svc.eqiad.wmnet
      ports:
        - protocol: tcp
          port: 4492
    - cidr: 10.2.1.14/32 # mobileapps.svc.codfw.wmnet
      ports:
        - protocol: tcp
          port: 4102
    - cidr: 10.2.2.14/32 # mobileapps.svc.eqiad.wmnet
      ports:
        - protocol: tcp
          port: 4102
    - cidr: 10.2.2.23/32 # linkrecommendation.discovery.wmnet (eqiad)
      ports:
        - protocol: tcp
          port: 4006
    - cidr: 10.2.1.23/32 # linkrecommendation.discovery.wmnet (codfw)
      ports:
        - protocol: tcp
          port: 4006
    - cidr: 10.2.2.63/32 # inference.discovery.wmnet (eqiad)
      ports:
        - protocol: tcp
          port: 30443
    - cidr: 10.2.1.63/32 # inference.discovery.wmnet (codfw)
      ports:
        - protocol: tcp
          port: 30443
    - cidr: 10.2.1.58/32 # inference-staging.svc.codfw.wmnet (codfw)
      ports:
        - protocol: tcp
          port: 30443
    - cidr: 10.2.2.80/32 # device-analytics.discovery.wmnet (eqiad)
      ports:
        - protocol: tcp
          port: 4972
    - cidr: 10.2.1.80/32 # device-analytics.discovery.wmnet (codfw)
      ports:
        - protocol: tcp
          port: 4972
    - cidr: 10.2.1.84/32 # k8s-ingress-ml-serve.svc.codfw.wmnet
      ports:
        - protocol: tcp
          port: 31443
    - cidr: 10.2.2.84/32 # k8s-ingress-ml-serve.svc.eqiad.wmnet
      ports:
        - protocol: tcp
          port: 31443
    - cidr: 10.2.1.59/32 # mwdebug.svc.codfw.wmnet
      ports:
        - protocol: tcp
          port: 4444
    - cidr: 10.2.2.59/32 # mwdebug.svc.eqiad.wmnet
      ports:
        - protocol: tcp
          port: 4444
    - cidr: 10.2.1.75/32 # mw-web.svc.codfw.wmnet
      ports:
        - protocol: tcp
          port: 4450
    - cidr: 10.2.2.75/32 # mw-web.svc.eqiad.wmnet
      ports:
        - protocol: tcp
          port: 4450
    - cidr: 10.2.1.82/32 # rest-gateway.svc.codfw.wmnet
      ports:
        - protocol: tcp
          port: 4113
    - cidr: 10.2.2.82/32 # rest-gateway.svc.eqiad.wmnet
      ports:
        - protocol: tcp
          port: 4113

external_services: ~
