app:
  version: 1.5.0-2026-06-03-154644-f7b9521b2dc3e22950dcddb1477998ee96e54279

external_services:
  kafka:
  - test-eqiad
  cas:
  - idp

auth_proxy:
  httpd_cas:
    site:
      server_name: kafka.wikimedia.org
      cas_root_proxied_as: https://kafka.wikimedia.org

ingress:
  gatewayHosts:
    default: "kafka-ui"
    extraFQDNs:
    - kafka.wikimedia.org
