config:
  mm:
    source: main-eqiad
    target: jumbo-eqiad
    # Blacklist change-prop topics. We don't need them in jumbo.
    # Also blacklist cirrusSearch related jobs.  These have unexplained HUGE messages.
    # and generally any mediawiki.job message. We already exclude them from data-lake
    # ingestion.
    topics: '^(?!.*change-prop\.|.*changeprop\.|.*cpjobqueue\.|.*mediawiki\.job\.).+$'
    flags:
      streams: 12

# We run 5*12=60 consumer threads
resources:
  replicas: 5

external_services:
  kafka:
  - main-eqiad
  - jumbo-eqiad
