config:
  mm:
    source: jumbo-eqiad
    target: test-eqiad
    topics: '^((eqiad|codfw)\.mediawiki\.revision-create)$'
    flags:
      streams: 2

external_services:
  kafka:
  - jumbo-eqiad
  - test-eqiad
