templates:
  default: &default
    chart: wmf-stable/kserve-crd-minimal
    namespace: kserve
    missingFileHandler: Warn
    installedTemplate: "{{`{{ if hasKey .Environment.Values \"install_kserve_crd_minimal\" }}{{ .Environment.Values.install_kserve_crd_minimal }}{{ else }}{{ false }}{{end}}`}}"

releases:
  - name: kserve-crd-minimal
    <<: *default
    needs:
      - kube-system/namespaces
