templates:
  default: &default
    chart: wmf-stable/kserve-crd-minimal
    namespace: kserve
    missingFileHandler: Warn
    # CRDs are installed whenever any KServe-related feature is enabled
    installedTemplate: "{{`{{ if hasKey .Environment.Values \"install_knative\" }}{{ .Environment.Values.install_knative }}{{ else if hasKey .Environment.Values \"install_kserve\" }}{{ .Environment.Values.install_kserve }}{{ else if hasKey .Environment.Values \"install_kserve_resources\" }}{{ .Environment.Values.install_kserve_resources }}{{ else }}{{ false }}{{end}}`}}"

releases:
  - name: kserve-crd-minimal
    <<: *default
    needs:
      - kube-system/namespaces
