apiVersion: v2
description: Helm chart for the maps vector tile server in WMF
name: tegola-vector-tiles
version: 0.1.24
kubeVersion: ">=1.16"
keywords:
  - maps
  - vector-tiles
  - vector-server
  - tegola
home: https://wikitech.wikimedia.org/wiki/Maps/v2
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/operations/software/tegola,general
team: https://wikitech.wikimedia.org/wiki/Content_Transform_Team
maintainers:
  - name: Yiannis Giannelos
    email: ygiannelos@wikimedia.org
  - name: Luca Toscano
    email: ltoscano@wikimedia.org
  - name: Effie Mouzeli
    email: effie@wikimedia.org