opensearchCluster:
  general:
    serviceName: "opensearch-ttmserver-test"
    image: docker-registry.wikimedia.org/repos/data-engineering/opensearch:2026-05-13-143357-2b2e022d3e2756b0dbd31d66e341a587f5d3b8d7-production2
  anonymous_all_indices: true

certificate:
  extraFQDNs:
  - opensearch-ttmserver-test.discovery.wmnet
