apiVersion: v2
description: A Helm chart for the deployment of the queryhammer
name: wdqs-queryhammer
version: 1.0.0
home: https://gitlab.wikimedia.org/repos/wikidata-platform/queryhammer
team: https://www.mediawiki.org/wiki/Wikidata_Platform
maintainers:
  - name: Lindsay Erickson
    email: lerickson@wikimedia.org
  - name: Gabriele Modena
    email: gmodena@wikimedia.org
  - name: Sebastian Trueg
    email: trueg@wikimedia.org
sources:
  - https://gitlab.wikimedia.org/repos/wikidata-platform/queryhammer
keywords:
  - wikidata
  - wdqs
