apiVersion: v2
description: Helm chart for datasets-config on dse-k8s infrastructure
kubeVersion: ">=1.12"
name: datasets-config
version: 0.0.17
keywords:
  - config
home: https://wikitech.wikimedia.org/wiki/Config_Store_Nitro
team: https://www.mediawiki.org/wiki/Data_Platform_Engineering
sources:
  - https://gitlab.wikimedia.org/repos/data-engineering/dataset-config-store-service
maintainers:
  - name: Thomas Chin
    email: tchin@wikimedia.org
  - name: Gabriele Modena
    email: gmodena@wikimedia.org
