#!/usr/bin/env python3
import os
import unittest

from smokepy.http import *
from smokepy import env

import helpers

# An origin to use in tests.
TEST_ORIGIN = "http://just.a.test"

# Headers to force a request to be limited
DENY_LIMIT_HEADERS = {
    "x-wmf-user-id": "Danese",
    "x-wmf-ratelimit-class": "DENY",
    "x-wmf-ratelimit-policy-1": "DENY",
}

class CorsTest(unittest.TestCase):

    target_url = None
    probe_config = None
    upstream_endpoint = None
    rb_compat_endpoint = None

    @classmethod
    def setUpClass(cls):
        CorsTest.probe_config = env.values.get("smokepy.gateway")
        CorsTest.target_url = helpers.getTargetUrl(CorsTest.probe_config)
        helpers.checkHealthz(CorsTest.target_url)

        CorsTest.upstream_endpoint = CorsTest.probe_config.get('cors_upstream_endpoint')
        CorsTest.rb_compat_endpoint = CorsTest.probe_config.get('cors_rb_compat_endpoint')

        if not CorsTest.upstream_endpoint:
            raise ValueError("cors_upstream_endpoint is not configured")
        if not CorsTest.rb_compat_endpoint:
            raise ValueError("cors_rb_compat_endpoint is not configured")

        print(f"Running CORS tests on {CorsTest.target_url}")
        print(f"  upstream endpoint:  {CorsTest.upstream_endpoint}")
        print(f"  rb compat endpoint: {CorsTest.rb_compat_endpoint}")

    def setUp(self):
        headers = CorsTest.probe_config.get("headers", {})
        self.target = Target(CorsTest.target_url, headers=headers)

    def assert_local_response_cors_headers_set(self, resp, origin):
        """Assert CORS headers are set correctly for a response generated by Envoy."""
        self.assertEqual("true", resp.headers.get("Access-Control-Allow-Credentials"),
            "expected Access-Control-Allow-Credentials: true")
        self.assertEqual(origin, resp.headers.get("Access-Control-Allow-Origin"),
            "expected Access-Control-Allow-Origin to echo the request origin")
        expose_headers = resp.headers.get("Access-Control-Expose-Headers") or ""
        self.assertIn("Retry-After", expose_headers, "expected Retry-After in Access-Control-Expose-Headers")
        self.assertIn("WWW-Authenticate", expose_headers, "expected WWW-Authenticate in Access-Control-Expose-Headers")

    def assert_rb_compat_cors_headers_set(self, resp):
        self.assertEqual("*", resp.headers.get("access-control-allow-origin"),
            "expected access-control-allow-origin: *")
        self.assertIn("GET,HEAD", resp.headers.get("access-control-allow-methods"),
            "expected access-control-allow-methods")
        self.assertIn("api-user-agent", resp.headers.get("access-control-allow-headers"),
            "expected access-control-allow-headers")

    def assert_headers_absent(self, resp, *headers):
        """Assert that the given headers are absent """
        for h in headers:
            self.assertIsNone(resp.headers.get(h), f"expected no {h} header")

    def test_envoy_error_response_with_origin(self):
        """Expect CORS headers for Envoy-generated responses (e.g. 429 for rate limits)."""

        headers = {
            "origin": TEST_ORIGIN, # should trigger CORS headers
            **DENY_LIMIT_HEADERS, # force a 429
        }
        resp = self.target.get(CorsTest.upstream_endpoint, headers=headers)
        self.assertEqual(429, resp.status, "expected 429 for forced rate limit")
        self.assert_local_response_cors_headers_set(resp, TEST_ORIGIN)

    def test_envoy_error_without_origin(self):
        """Expect no CORS headers when no Origin header is present in the request."""

        headers = {
            **DENY_LIMIT_HEADERS, # force a 429
        }
        resp = self.target.get(CorsTest.upstream_endpoint, headers=headers)
        self.assertEqual(429, resp.status, "expected 429 for forced rate limit")
        self.assert_headers_absent(resp, "Access-Control-Allow-Credentials", "Access-Control-Expose-Headers")

    def test_envoy_error_for_options_request(self):
        """Expect no CORS headers for OPTIONS requests."""

        headers = {
            ":method": "OPTIONS", # should suppress CORS headers
            "origin": TEST_ORIGIN,
            **DENY_LIMIT_HEADERS, # force a 429
        }
        resp = self.target.get(CorsTest.upstream_endpoint, headers=headers)
        self.assertEqual(429, resp.status, "expected 429 for forced rate limit")
        self.assert_headers_absent(resp, "Access-Control-Allow-Credentials", "Access-Control-Expose-Headers")

    def test_upstream_response(self):
        """Expect no CORS headers on upstream response."""
        headers = { "origin": TEST_ORIGIN, }
        resp = self.target.get(CorsTest.upstream_endpoint, headers=headers)
        self.assertEqual(200, resp.status, "expected status 200 OK")
        self.assert_headers_absent(resp, "Access-Control-Allow-Credentials", "Access-Control-Expose-Headers")

    def test_upstream_response_rb_compat(self):
        """Routes with rb_response_headers should send restbase compatibility headers."""
        headers = { "origin": TEST_ORIGIN, }
        resp = self.target.get(CorsTest.rb_compat_endpoint, headers=headers)
        self.assertEqual(200, resp.status, "expected status 200 OK")
        self.assert_rb_compat_cors_headers_set(resp)
        self.assert_headers_absent(resp, "Access-Control-Allow-Credentials")

def main():
    unittest.main()

#############################################
helpers.initEnv()

if __name__ == "__main__":
    main()
