apiVersion: v2
description: An auxiliary service for generating histograms from Redis databases.
name: redioscope
version: 0.2.2 # capture window duration
keywords:
  - api-gateway
  - redis
home: https://wikitech.wikimedia.org/wiki/Redioscope
sources:
  - https://gitlab.wikimedia.org/repos/mediawiki/services/redioscope
team: https://wikitech.wikimedia.org/wiki/MediaWiki_Interfaces_Team
maintainers:
  - name: Daniel Kinzler
    email: dkinzler@wikimedia.org
