inference_services:
  editing-suggestions:
    predictor:
      image: "machinelearning-liftwing-inference-services-editing-suggestions"
      image_version: "2026-07-06-083804-publish"
      custom_env:
        - name: STORAGE_URI
          value: "s3://wmf-ml-models/editing-suggestions/v1/20260819111554/"
        - name: MODEL_NAME
          value: "editing-suggestions"
      container:
        resources:
          limits:
            cpu: "8"
            memory: 16Gi
            ephemeral-storage: 15Gi
          requests:
            cpu: "2"
            memory: 4Gi
            ephemeral-storage: 10Gi

  tts:
    predictor:
      config:
        containerConcurrency: 1
        minReplicas: 1
        maxReplicas: 4
        timeout: 600
      image: "machinelearning-liftwing-inference-services-tts"
      image_version: "2026-07-31-123132-publish"
      custom_env:
        - name: MODEL_NAME
          value: "tts"
        - name: STORAGE_URI
          value: "s3://wmf-ml-models/tts/"
        - name: KOKORO_THREADS
          value: "8"
        - name: W2V2_THREADS
          value: "2"
      container:
        resources:
          limits:
            cpu: "8"
            memory: 16Gi
            ephemeral-storage: 15Gi
          requests:
            cpu: "8"
            memory: 16Gi
            ephemeral-storage: 10Gi

external_services_app_label_selector: app-wmf
external_services:
  cassandra:
  - ml-cache-a-eqiad
  - ml-cache-a-codfw
  - cassandra-dev-a-codfw
  - cassandra-dev-b-codfw
  - analytics-query-service-storage-a-codfw
  - analytics-query-service-storage-b-codfw
  - analytics-query-service-storage-a-eqiad
  - analytics-query-service-storage-b-eqiad
