inference_services:

  revertrisk-wikidata:
    predictor:
      image: "machinelearning-liftwing-inference-services-revertrisk-wikidata"
      image_version: "2026-01-12-112314-publish"
      custom_env:
        - name: MODEL_NAME
          value: "revertrisk-wikidata"
        - name: STORAGE_URI
          value: "s3://wmf-ml-models/revertrisk/wikidata/20251104121312/"
        - name: FORCE_HTTP
          value: "True"
        - name: WORKERS
          value: "8"
      container:
        resources:
          limits:
            cpu: "2"
            memory: 16Gi
          requests:
            cpu: "2"
            memory: 16Gi

  articlequality:
    predictor:
      image: "machinelearning-liftwing-inference-services-articlequality"
      image_version: "2025-10-16-103324-publish"
      custom_env:
        - name: MODEL_NAME
          value: "articlequality"
        - name: STORAGE_URI
          value: "s3://wmf-ml-models/articlequality/language-agnostic/20250425125943/"
        - name: FORCE_HTTP
          value: "True"
      container:
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi

  edit-check:
    predictor:
      config:
        maxReplicas: 1
        batcher:
          maxBatchSize: 32
          maxLatency: 100
      image: "machinelearning-liftwing-inference-services-edit-check"
      image_version: "2025-06-25-142517-publish"
      custom_env:
        - name: MODEL_NAME
          value: "edit-check-staging"
        - name: STORAGE_URI
          value: "s3://wmf-ml-models/edit-check/peacock/"
        - name: MODEL_VERSION
          value: "v1"
        - name: USE_METADATA
          value: "true"
      container:
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi

external_services_app_label_selector: app-wmf
external_services:
  cassandra:
  - ml-cache-a-eqiad
  - ml-cache-a-codfw
  - cassandra-dev-a-codfw
  - cassandra-dev-b-codfw
  - analytics-query-service-storage-a-codfw
  - analytics-query-service-storage-b-codfw
  - analytics-query-service-storage-a-eqiad
  - analytics-query-service-storage-b-eqiad
