inference_services:

  # policy-violation isvc
  cope-a-9b:
    predictor:
      image: "machinelearning-liftwing-inference-services-policy-violation-cope-a-9b"
      image_version: "2026-03-12-152219-publish"
      custom_env:
        - name: MODEL_NAME
          value: "cope-a-9b"
        - name: STORAGE_URI
          value: "s3://wmf-ml-models/cope-a-9b-merged/"
        - name: MODEL_PATH
          value: "/mnt/models"
        - name: TRUST_REMOTE_CODE
          value: "False"
        - name: MAX_MODEL_LEN
          value: 4096
      container:
        resources:
          limits:
            cpu: "6"
            memory: 16Gi
            amd.com/gpu: "1"
          requests:
            cpu: "6"
            memory: 16Gi
            amd.com/gpu: "1"
      config:
        maxReplicas: 1
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "mi300x-experiments"
            effect: "NoSchedule"
          - key: "dedicated"
            operator: "Equal"
            value: "mi300x-experiments"
            effect: "NoExecute"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "kubernetes.io/hostname"
                      operator: "In"
                      values:
                        - "ml-serve1012.eqiad.wmnet"

  # policy-violation isvc
  gpt-oss-safeguard-20b:
    predictor:
      config:
        maxReplicas: 1
      image: "machinelearning-liftwing-inference-services-policy-violation-gpt-oss-safeguard"
      image_version: "2026-03-20-092036-publish"
      custom_env:
        - name: MODEL_NAME
          value: "gpt-oss-safeguard-20b"
        - name: STORAGE_URI
          value: "s3://wmf-ml-models/gpt-oss-safeguard-20b/"
        - name: TIKTOKEN_ENCODINGS_BASE
          value: "/mnt/models/tiktoken_encodings/"
        - name: TRUST_REMOTE_CODE
          value: "False"
        - name: GPU_MEMORY_UTILIZATION
          value: "0.95"
        - name: MAX_MODEL_LEN
          value: "16384"
        - name: MAX_NUM_BATCHED_TOKENS
          value: "8192"
        - name: MAX_NUM_SEQS
          value: "32"
        - name: BLOCK_SIZE
          value: "64"
        - name: ATTENTION_BACKEND
          value: "ROCM_AITER_UNIFIED_ATTN"
        - name: VLLM_ROCM_USE_AITER
          value: "1"
        - name: MAX_JOBS
          value: "1"
        - name: AMDGCN_USE_BUFFER_OPS
          value: "0"
      containers:
        resources:
          limits:
            cpu: "6"
            memory: 24Gi
            amd.com/gpu: "1"
          requests:
            cpu: "6"
            memory: 24Gi
            amd.com/gpu: "1"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "8Gi"
      config:
        maxReplicas: 1
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "mi300x-experiments"
            effect: "NoSchedule"
          - key: "dedicated"
            operator: "Equal"
            value: "mi300x-experiments"
            effect: "NoExecute"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "kubernetes.io/hostname"
                      operator: "In"
                      values:
                        - "ml-serve1012.eqiad.wmnet"
