app:
  waitForMigrations: true
  args: ["api-server", "--pid" , "/tmp/airflow-webserver.pid"]
  readiness_probe:
    httpGet:
      path: /api/v2/monitor/health

dagProcessor:
  enabled: true

config:
  airflow:
    config:
      scheduler:
        standalone_dag_processor: true
