config:
  airflow:
    instance_name: test-k8s
    auth:
      op_ldap_role: ~
    config:
      kubernetes_executor:
        worker_pods_creation_batch_size: 32
      kerberos:
        principal: analytics/airflow-test-k8s.discovery.wmnet
  geoip:
    enabled: true
  oidc:
    idp_server: idp-test.wikimedia.org

app: # the webserver
  version: &base-image-version airflow-2.11.2-py3.11-2026-04-16-134304-f4802bd4391b8fc561804913728472d5a2721d42@sha256:976f939064787fa65c1c551e72f697120e611e5610441d6869c7523d723d429b
  executor_pod_image_version: *base-image-version
  requests:
    memory: 4Gi
  limits:
    memory: 4Gi

scheduler:
  requests:
    cpu: 8
    memory: 4Gi
  limits:
    cpu: 8
    memory: 4Gi

external_services:
  webserver:
    # We login to airflow-test-k8s via the idp-test CAS server
    cas: [idp-test]
  task-pod:
    dumps: [wikimedia]

ingress:
  gatewayHosts:
    default: "airflow-test-k8s"
    extraFQDNs:
    - airflow-test-k8s.wikimedia.org
