apiVersion: v2
name: kserve
description: WMF KServe setup
type: application
version: 0.3.0
appVersion: 0.11.2
keywords:
  - ml
home: https://wikitech.wikimedia.org/wiki/Machine_Learning/LiftWing/KServe
sources:
  - https://gerrit.wikimedia.org/r/admin/repos/operations/docker-images/production-images
team: https://wikitech.wikimedia.org/wiki/Machine_Learning
maintainers:
  - name: Tobias Klausmann
    email: TKlausmann@wikimedia.org
