main_app:
  requests:
    cpu: 3
  limits:
    cpu: 3
  # Use a local-disk tmp to improve performance for
  # large files. T292322
  volumes:
    - name: local-disk-tmp
      emptyDir: {}
  volumeMounts:
    - name: local-disk-tmp
      mountPath: /tmp
shellbox:
  flavour: media83

service:
  deployment: production

mesh:
  enabled: true
  public_port: 4015
  tracing:
    enabled: true
    sampling: 10

php:
  workers: 4

resources:
  replicas: 8

networkpolicy:
  egress:
    enabled: true
    dst_nets:
      # shellbox-media needs to be able to communicate with swift in order to
      # fetch files so it can extract metadata
      # ms-fe.svc.eqiad.wmnet.
      - cidr: 10.2.2.27/32
        ports:
          - protocol: TCP
            port: 443
      # ms-fe.svc.codfw.wmnet.
      - cidr: 10.2.1.27/32
        ports:
          - protocol: TCP
            port: 443

discovery:
  listeners:
    - swift-eqiad
    - swift-codfw
