app:
  version: 2026-08-08-044844-3bdefe6ed4c51d628a2c78132e8c7262a68a1007@sha256:7a1cf422b34b6ccde4b47161bb3ed4c2f22900975f099a9ac748a10ad46fa323

config:
  hdfs:
    dfs.nameservices: analytics-hadoop
    dfs.internal.nameservices: analytics-hadoop
    dfs.client.failover.proxy.provider.analytics-hadoop: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
    dfs.ha.namenodes.analytics-hadoop: an-master1003-eqiad-wmnet,an-master1004-eqiad-wmnet
    dfs.namenode.servicerpc-address.analytics-hadoop.an-master1003-eqiad-wmnet: an-master1003.eqiad.wmnet:8040
    dfs.namenode.servicerpc-address.analytics-hadoop.an-master1004-eqiad-wmnet: an-master1004.eqiad.wmnet:8040
    dfs.namenode.rpc-address.analytics-hadoop.an-master1003-eqiad-wmnet: an-master1003.eqiad.wmnet:8020
    dfs.namenode.rpc-address.analytics-hadoop.an-master1004-eqiad-wmnet: an-master1004.eqiad.wmnet:8020
    dfs.namenode.http-address.analytics-hadoop.an-master1003-eqiad-wmnet: an-master1003.eqiad.wmnet:50070
    dfs.namenode.http-address.analytics-hadoop.an-master1004-eqiad-wmnet: an-master1004.eqiad.wmnet:50070

  hadoop:
    fs.defaultFS: hdfs://analytics-hadoop/

ingress:
  gatewayHosts:
    default: "blunderbuss"

external_services:
  archiva:
  - legacy
  hadoop-master:
  - analytics
  hadoop-worker:
  - analytics

common_images:
  kerberos:
    version: 2024-11-22-165659-58a0855db4580609a7dbced0ac450acde29947b5@sha256:1094847900f362504d7f75ccc4e1864e7062784ddc8170999745f19a80fa3e6e
